In [5]:
import requests
from datetime import datetime
import os
from dotenv import load_dotenv
import pandas as pd
import json
import re
import html
load_dotenv()
api_key = os.getenv("API_KEY")

In [4]:
class ExtractChampionData:

    def __init__(self):
        self.last_version = self.get_latest_version()
        self.list_champ = self.get_all_champ_general_data()
        self.list_champ = list(self.list_champ.keys())

    def get_latest_version(self):
        """Get the last version of the game"""
        url = "https://ddragon.leagueoflegends.com/api/versions.json"
        rep = requests.get(url).json()
        latest = rep[0]
        return latest

    def get_all_champ_general_data(self):
        """Get the champion data"""
        url = f"https://ddragon.leagueoflegends.com/cdn/{self.last_version}/data/fr_FR/champion.json"
        resp = requests.get(url).json()
        return resp['data']
    
    def get_details_champ_data(self):
        """Get detail champion data"""
        data = []
        for champ in self.list_champ:
            url = f"https://ddragon.leagueoflegends.com/cdn/{self.last_version}/data/fr_FR/champion/{champ}.json"
            resp = requests.get(url).json()['data']
            data.append(resp[champ])
        return data
    
    def get_champion_mastery(self, puuid : str):
        """Get all champion mastery entries sorted by number of champion points descending."""

        api_url = f"https://euw1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/{puuid}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
        

    # def download_all_png_champion(self):
    #     """Download all champions pictures"""
    #     for champ in self.list_champ:
    #         url = f"https://ddragon.leagueoflegends.com/cdn/{self.last_version}/img/champion/{champ}.png"
    #         path_save = fr"C:\Users\najim\Documents\Projets\LeagueOfLegends\images\{champ}.png"

    #         resp = requests.get(url)
    #         with open(path_save, "wb") as file:
    #             file.write(resp.content)

In [89]:
class TransformChampionData:

    def __init__(self):
        self.keys_to_drop = ['image', 'skins', 'blurb']
        self.table_champion = ['key', 'name', 'title', 'lore', 'tags', 'partype']
        self.table_champ_passive = ['key', 'passive']
        self.table_champ_info = ['key', 'info', 'allytips', 'enemytips']
        self.table_champ_spells = ['key', 'spells']
        self.table_champ_stats = ['key', 'stats']
    
    def drop_keys(self, data : list) -> list:
        new_data = []
        for dict_champ in data:
            dict_champ = {k: v for k,v in dict_champ.items() if k not in self.keys_to_drop}
            new_data.append(dict_champ)
        return new_data
    
    def dispatch_data(self, data : list):
        table_champion = []
        table_champ_passive = []
        table_champ_info = []
        table_champ_spells = []
        table_champ_stats = []
        
        for dict_champ in data:
            champion = {k: v for k,v in dict_champ.items() if k in self.table_champion}
            champ_passive = {k: v for k,v in dict_champ.items() if k in self.table_champ_passive}
            champ_info = {k: v for k,v in dict_champ.items() if k in self.table_champ_info}
            champ_spells = {k: v for k,v in dict_champ.items() if k in self.table_champ_spells}
            champ_stats = {k: v for k,v in dict_champ.items() if k in self.table_champ_stats}

            table_champion.append(champion)
            table_champ_passive.append(champ_passive)
            table_champ_info.append(champ_info)
            table_champ_spells.append(champ_spells)
            table_champ_stats.append(champ_stats)
            
        return table_champion, table_champ_passive, table_champ_info, table_champ_spells, table_champ_stats
    
    def split_stats(self, data : list):
        stats_cst, stats_up = [], []
        for stat in data:
            cst = {k:v for k,v in stat.items() if "perlevel" not in k}
            up = {k: v for k, v in stat.items() if "perlevel" in k or "key" in k}
            stats_cst.append(cst)
            stats_up.append(up)
        return stats_cst, stats_up

    def listing_into_text(self, data : list, key : str, sep : str = " "):
        new_data = []
        for champ in data:
            new_value = f"{sep}".join(champ[key])
            champ[key] = self._clean_text(new_value)
            new_data.append(champ)
        return new_data

    def dict_into_first_level(self, data : list, key_to_flat : str) -> list:
        new_data = []
        for champ in data:
            base = {k: v for k, v in champ.items() if k != key_to_flat}
            base.update(champ.get(key_to_flat, {}))
            new_data.append(base)
        return new_data
    
    def pop_key(self, data : list, key_to_remove : list[str]) -> list:
        new_data = []
        for i in data:
            for key in key_to_remove:
                d = i.pop(key, None)
            new_data.append(i)
        return new_data
    
    def _clean_text(self, desc : str) -> str:
        desc = re.sub(r"<[^>]+>|<[a-z]>", " ", desc)
        desc = re.sub(r"\xa0", " ", desc)
        desc = re.sub(r"_ClientTooltipWrapper|Wrapper", "", desc)
        desc = re.sub(r"\{\{.*?\}\}", "XX", desc)
        desc = re.sub(r"XX$", "", desc)
        desc = re.sub(r"[ ]+", " ", desc)
        return desc

    def text_cleaning(self, data : list, key : str) -> list:
        clean = []
        for champ in data:
            desc = self._clean_text(champ[key])
            champ[key] = desc
            clean.append(champ)
        return clean
    
    def clean_spells_data(self, data: list):
        new_data = []
        for champ in data:
            idchamp = champ['key']
            spells = champ['spells']

            spells = self.pop_key(
                spells,
                key_to_remove=['leveltip', 'description', 'cooldown', 'cost', 'datavalues',
                    'effect', 'vars', 'image', 'effectBurn', 'range'])

            spells_clean = self.text_cleaning(spells, 'tooltip')
            spells_clean = self.text_cleaning(spells, 'name')
            spells_clean = self.text_cleaning(spells, 'id')

            for spell in spells_clean:
                spell['key'] = idchamp
                new_data.append(spell)

        return new_data
    
    def transform_to_df(self, data : list) -> pd.DataFrame:
        """Transforme une liste de dictionnaire en dataframe pandas"""
        return pd.DataFrame(data)

In [90]:
def pipeline_champion():
    """Pipeline d'application des méthodes d'extraction, de transformation et de chargement"""
    
    extract = ExtractChampionData()
    transform = TransformChampionData()

    details = extract.get_details_champ_data()
    details = transform.drop_keys(details)
    
    table_champion, table_champ_passive, table_champ_info, table_champ_spells, table_champ_stats = transform.dispatch_data(details)
    
    table_champion = transform.listing_into_text(table_champion, "tags", sep=' / ')
    table_champion = transform.text_cleaning(table_champion, key='lore')
    table_champion = transform.text_cleaning(table_champion, key='title')
    
    table_champ_info = transform.listing_into_text(table_champ_info, key="enemytips", sep=' ')
    table_champ_info = transform.listing_into_text(table_champ_info, key="allytips", sep=' ')
    table_champ_info = transform.dict_into_first_level(table_champ_info, key_to_flat='info')

    table_champ_passive = transform.dict_into_first_level(table_champ_passive, key_to_flat='passive')
    table_champ_passive = transform.pop_key(table_champ_passive, key_to_remove=['image'])
    table_champ_passive = transform.text_cleaning(table_champ_passive, key='name')
    table_champ_passive = transform.text_cleaning(table_champ_passive, key='description')

    table_champ_stats = transform.dict_into_first_level(table_champ_stats, key_to_flat='stats')
    table_champ_stats, table_champ_stats_up = transform.split_stats(table_champ_stats)

    table_champ_spells = transform.pop_key(table_champ_spells, key_to_remove= ['leveltip', 'description', 'cooldown', 'cost', 'datavalues', 
                                                                               'effect', 'vars', 'image', 'effectBurn', 'range'])
    table_champ_spells = transform.clean_spells_data(table_champ_spells)

    table_champion = transform.transform_to_df(table_champion)
    table_champ_info = transform.transform_to_df(table_champ_info)
    table_champ_passive = transform.transform_to_df(table_champ_passive)
    table_champ_stats = transform.transform_to_df(table_champ_stats)
    table_champ_stats_up = transform.transform_to_df(table_champ_stats_up)
    table_champ_spells = transform.transform_to_df(table_champ_spells)
    
    return table_champion, table_champ_passive, table_champ_info, table_champ_spells, table_champ_stats, table_champ_stats_up

table_champion, table_champ_passive, table_champ_info, table_champ_spells, table_champ_stats, table_champ_stats_up = pipeline_champion()

In [91]:
table_champ_spells

,id,name,tooltip,maxrank,cooldownBurn,costBurn,costType,maxammo,rangeBurn,resource,key
0,AatroxQ,Épée des Darkin,"Aatrox abat son épée, infligeant XX pts de dég...",5,14/12/10/8/6,0,Pas de coût,-1,25000,Pas de coût,266
1,AatroxW,Chaînes infernales,"Aatrox lance une chaîne, ralentissant le premi...",5,20/18/16/14/12,0,Pas de coût,-1,825,Pas de coût,266
2,AatroxE,Ruée obscure,Passive : Aatrox récupère des PV équivalents ...,5,9/8/7/6/5,0,Pas de coût,-1,25000,Pas de coût,266
3,AatroxR,Fossoyeur des mondes,"Aatrox révèle sa vraie forme démoniaque, effra...",3,120/100/80,0,Pas de coût,-1,25000,Pas de coût,266
4,AhriQ,Orbe d'illusion,"Ahri lance son orbe et le ramène vers elle, in...",5,7,55/65/75/85/95,{{ abilityresourcename }},-1,970,{{ cost }} {{ abilityresourcename }},103
...,...,...,...,...,...,...,...,...,...,...,...
683,ZoeR,Bond dimensionnel,Zoé se téléporte à un endroit proche pendant 1...,3,11/8/5,40,{{ abilityresourcename }},-1,575,{{ cost }} {{ abilityresourcename }},142
684,ZyraQ,Épines funestes,Zyra répand des ronces dans le sol et provoque...,5,7/6.5/6/5.5/5,55,{{ abilityresourcename }},-1,800,{{ cost }} {{ abilityresourcename }},143
685,ZyraW,Croissance incontrôlée,Zyra plante une graine qui dure XX sec. Quand ...,5,0,0,1 graine,2,850,1 graine,143
686,ZyraE,Racines fixatrices,Zyra lance des racines qui immobilisent les en...,5,11,70/75/80/85/90,{{ abilityresourcename }},-1,1100,{{ cost }} {{ abilityresourcename }},143
687,ZyraR,Ronces étrangleuses,"Zyra invoque la fureur de la nature, créant de...",3,110/100/90,100,{{ abilityresourcename }},-1,700,{{ cost }} {{ abilityresourcename }},143

In [92]:
for i in table_champ_spells['tooltip']:
    print(i)

Aatrox abat son épée, infligeant XX pts de dégâts physiques . Si l'ennemi est touché par le tranchant, il est brièvement projeté dans les airs et subit XX pts de dégâts à la place. Cette compétence peut être réactivée deux fois, chaque coup changeant de forme et infligeant 25% de dégâts de plus que la précédente.
Aatrox lance une chaîne, ralentissant le premier ennemi touché de XX% pendant XX sec et infligeant XX pts de dégâts physiques . Les champions et les grands monstres doivent quitter la zone d'effet dans les XX sec sous peine d'être ramenés de force au point d'impact et de subir à nouveau les dégâts.
 Passive : Aatrox récupère des PV équivalents à XX des dégâts qu'il inflige aux champions. Active : Aatrox se rue dans une direction. Il peut utiliser cette compétence tout en lançant ses autres compétences.
Aatrox révèle sa vraie forme démoniaque, effrayant les sbires proches pendant XX sec et gagnant +XX% de vitesse de déplacement (ce bonus diminue en XX sec). Il gagne aussi +XX% de dégâts d'attaque et augmente ses soins personnels de XX% pendant la durée. Participer à l'élimination d'un champion prolonge la durée de cet effet de XX sec et réinitialise le bonus en vitesse de déplacement .
Ahri lance son orbe et le ramène vers elle, infligeant XX pts de dégâts magiques à l'aller et XX pts de dégâts bruts au retour.
Ahri libère 3 lucioles qui cherchent des ennemis proches pour leur infliger XX pts de dégâts magiques , et ces dégâts sont réduits à XX au-delà de la première luciole. Ahri gagne aussi +XX% de vitesse de déplacement , et ce bonus diminue en XX sec.
Ahri envoie un baiser qui charme le premier ennemi touché pendant XX sec et inflige XX pts de dégâts magiques .
Ahri se rue dans une direction en tirant XX projectiles essentiels sur les ennemis proches (les champions en priorité). Ces projectiles infligent XX pts de dégâts magiques chacun. Assaut spirituel peut être réactivé deux fois dans les XX sec. Pendant cette période, consommer l'essence d'un champion avec Vol essentiel prolonge de XX sec la fenêtre de réactivation et octroie une réactivation supplémentaire d' Assaut spirituel (stockage max : XX).
Akali lance des kunais dans un arc de cercle, infligeant XX pts de dégâts magiques . Les ennemis touchés au maximum de la portée sont ralentis de XX% pendant XX sec.
Akali lâche une bombe fumigène, créant un nuage de fumée qui s'étend et dure XX sec et gagnant +XX% de vitesse de déplacement (ce bonus diminue en XX sec). Akali augmente son énergie max de XX tant que le nuage de fumée est actif. Dans la fumée, Akali est invisible .
Akali fait un salto arrière en lançant un shuriken, infligeant XX pts de dégâts magiques et marquant le premier ennemi ou nuage de fumée touché. Akali peut réactiver cette compétence une fois pour se ruer vers la cible marquée, infligeant XX pts de dégâts magiques .
Akali passe par-dessus un champion ennemi, infligeant XX pts de dégâts magiques à tous les ennemis sur son chemin. Akali peut réactiver cette compétence après XX sec pour effectuer une percée, se ruant dans une direction et infligeant de XX à XX pts de dégâts magiques selon les PV manquants des ennemis.
Akshan lance un boomerang qui inflige XX pts de dégâts physiques et dont la portée augmente chaque fois qu'il touche un ennemi. Akshan gagne +XX de vitesse de déplacement (ce bonus diminue en XX sec) quand le boomerang touche un champion.
XX }}
 Première activation : Akshan tire un grappin qui s'accroche au premier élément de terrain touché. Deuxième activation : Akshan tourne autour du terrain, tirant à plusieurs reprises sur l'ennemi le plus proche pour infliger XX pts de dégâts physiques par tir. Troisième activation : Akshan plonge en lâchant la corde et tire un dernier coup. Entrer en contact avec un champion ennemi ou un élément du terrain met prématurément fin au balancement d'Akshan. Les éliminations de champions annulent le délai de récupération de cette compétence.
Akshan se verrouille sur un champion et commence à surcharger son pistolet pendant un maximum de XX sec, ce qui stocke jusqu'à XX balles. Réactivation : Akshan tire toutes les balles stockées, chacune infligeant au moins XX pts de dégâts physiques au premier ennemi ou bâtiment touché. Ces dégâts peuvent augmenter jusqu'à XX selon les PV manquants de la cible.
Alistar frappe le sol, projetant dans les airs les ennemis pendant XX sec et infligeant XX pts de dégâts magiques .
Alistar fonce dans un ennemi, le repoussant et lui infligeant XX pts de dégâts magiques .
Alistar piétine le sol, devient fantomatique et inflige XX pts de dégâts magiques aux ennemis proches en XX sec. Chaque pulsation qui blesse au moins un champion octroie un effet. À XX effets cumulés, la prochaine attaque d'Alistar contre un champion étourdit la cible pendant XX sec et inflige XX pts de dégâts magiques supplémentaires.
Alistar purge immédiatement toutes les entraves qui l'affectent et réduit les dégâts qu'il subit de XX% pendant XX sec.
 Frappe fourbe : Ambessa fait tourner ses lames devant elle, infligeant XX + XX des PV max en dégâts physiques aux ennemis touchés par le bord de l'attaque. Tous les autres ennemis subissent XX pts de dégâts. Toucher un ennemi prépare une Frappe fracassante . Frappe fracassante : Ambessa frappe le sol avec ses lames, infligeant XX + XX des PV max en dégâts physiques au premier ennemi touché. Tous les autres ennemis subissent XX pts de dégâts.
Ambessa gagne un bouclier de XX PV pendant XX sec et se protège pendant XX sec. Elle frappe ensuite le sol, infligeant XX pts de dégâts physiques aux ennemis proches. Ces dégâts sont augmentés à XX pts de dégâts physiques si elle a bloqué des dégâts d'un champion ennemi, d'un grand monstre ou d'un bâtiment.
Ambessa fait tourner ses chaînes autour d'elle, infligeant XX pts de dégâts physiques aux ennemis touchés et les ralentissant de XX% (diminue en XX sec). Utiliser Ruée des chiens-dragons à partir de cette compétence déclenche une frappe supplémentaire.
 Passive : Ambessa gagne %i:scaleAPen% +XX% de pénétration d'armure et ses compétences lui rendent des PV équivalents à XX des dégâts infligés . Active : Ambessa devient impossible à arrêter et se téléporte sur l'ennemi le plus éloigné sur une ligne droite, le neutralisant pendant XX sec avant de le projeter au sol, ce qui lui inflige XX pts de dégâts physiques et l' étourdit pendant XX sec.
Amumu lance une bandelette dans une direction, se tractant jusqu'au premier ennemi touché, l' étourdissant pendant XX sec et lui infligeant XX pts de dégâts magiques . Cette compétence a 2 charges.
 Activable/Désactivable : Amumu commence à pleurer, infligeant aux ennemis proches XX plus XX% des PV max en dégâts magiques chaque seconde et réinitialisant Malédiction .
 Passive : Amumu subit des dégâts physiques réduits de XX. De plus, quand Amumu est touché par une attaque, le délai de récupération de cette compétence est réduit de XX sec. Active : Amumu pique une colère, infligeant XX pts de dégâts magiques aux ennemis proches.
Amumu répand ses bandelettes autour de lui, étourdissant les ennemis pendant XX sec, leur infligeant XX pts de dégâts magiques et appliquant Malédiction .
Anivia tire un gros bloc de glace, infligeant XX pts de dégâts magiques et gelant les ennemis pendant XX sec, ce qui les ralentit de XX%. Une fois arrivé au bout de sa portée, le bloc de glace explose, étourdissant les ennemis pendant XX sec et infligeant XX pts de dégâts magiques . Anivia peut réactiver cette compétence pour faire exploser le bloc de glace prématurément.
Anivia invoque un mur de glace de XX unités de large. Le mur dure XX sec, puis fond.
Anivia frappe un ennemi avec un vent glaçant, infligeant XX pts de dégâts magiques . Contre les ennemis gelés , Anivia inflige XX pts de dégâts magiques .
 Activable/Désactivable : Anivia fait tomber une pluie de glace et de grêle dans une zone, ralentissant les ennemis de XX% et infligeant XX pts de dégâts magiques par seconde . La zone affectée s'étend pendant XX sec. Quand la zone atteint sa taille maximale, elle gèle les ennemis, les ralentissant de XX%, et elle inflige XX pts de dégâts magiques par seconde .
Annie lance une boule de feu, infligeant XX pts de dégâts magiques . Si la cible meurt, Annie récupère le coût en mana de la compétence et son délai de récupération est réduit de 50%.
Annie projette une vague de feu qui inflige XX pts de dégâts magiques .
Annie octroie à un champion allié un bouclier de XX PV pendant XX sec et +XX vitesse de déplacement (diminuant progressivement) pendant XX sec. Tant que le bouclier est actif, les ennemis qui lancent une attaque ou une compétence sur l'allié protégé subissent XX pts de dégâts magiques (une fois par bouclier). Tibbers gagne toujours les effets de Bouclier en fusion quand il est invoqué.
 Passive : Annie gagne +XX% de pénétration magique. Annie invoque son ours Tibbers, infligeant XX pts de dégâts magiques . Pendant les XX prochaines secondes, Tibbers brûle les ennemis proches en leur infligeant XX pts de dégâts magiques par seconde . Tibbers devient enragé quand il est invoqué, quand Annie étourdit un champion ennemi et quand Annie meurt. Il gagne alors +275% de vitesse d'attaque et +100% de vitesse de déplacement (ce bonus diminue en 3 sec). Réactivation : permet de donner des ordres manuellement à Tibbers.

Échange les armes principale et secondaire pour s'équiper de : Gravitum .

Aphelios tire un rayon de lune concentré qui explose au contact d'un champion et qui inflige XX pts de dégâts physiques aux ennemis proches. Aphelios attaque ensuite tous les champions touchés avec son arme principale. XX }}
 Passive : les attaques d'Ashe lui octroient un effet pendant XX sec. À XX effets cumulés, elle peut activer cette compétence. Active : Ashe gagne +XX% de vitesse d'attaque et ses attaques infligent XX de dégâts pendant XX sec.
Ashe tire une salve de XX flèches, chacune infligeant XX pts de dégâts physiques . Les ennemis peuvent être touchés par plusieurs flèches, mais ils ne subissent les dégâts que de la première.
Ashe envoie un faucon n'importe où sur la carte pour obtenir la vision d'une zone pendant 5 sec. Cela révèle aussi le chemin sur son trajet. Cette compétence a 2 charges (XX sec de rechargement).
Ashe tire une flèche de cristal qui étourdit le premier champion touché et inflige XX pts de dégâts magiques . La durée de l' étourdissement augmente avec la distance parcourue, jusqu'à un maximum de XX sec. Les ennemis proches sont ralentis par Tir givrant .
Aurelion Sol crache du feu stellaire pendant un maximum de XX sec, infligeant XX pts de dégâts magiques par seconde au premier ennemi touché et XX% de ces dégâts aux ennemis proches. À chaque seconde de canalisation sur un même ennemi, une surcharge inflige des dégâts magiques équivalents à XX plus XX des PV max . Si la cible est un champion, cette surcharge collecte aussi XX poussière d'étoile .
Aurelion Sol s'envole dans la direction ciblée. Pendant le vol, Souffle de lumière n'a ni délai de récupération ni durée maximale de canalisation et ses dégâts fixes sont augmentés de XX%. Si un champion meurt dans les XX sec après avoir été blessé par Aurelion Sol, le délai de récupération de cette compétence est réduit de XX%. Réactivation : met fin prématurément au vol.
Aurelion Sol invoque un trou noir, infligeant XX pts de dégâts magiques par seconde et attirant les ennemis vers son centre pendant XX sec. Au centre du trou noir, les ennemis qui ont moins de XX% de leurs PV max meurent instantanément. Le trou noir absorbe de la poussière d'étoile chaque fois qu'un ennemi meurt dans son rayon et à chaque seconde qu'un champion ennemi passe dans son rayon.
Aurelion Sol fait s'abattre une étoile au sol, infligeant XX pts de dégâts magiques , étourdissant les ennemis pendant XX sec et collectant XX poussières d'étoile par champion touché. Collecter XX poussières d'étoile transforme la prochaine Étoile finale en Apocalypse . Apocalypse : Aurelion Sol fait s'abattre la puissance d'une constellation, infligeant XX pts de dégâts magiques dans une zone plus large, projetant dans les airs les ennemis touchés pendant XX sec et provoquant une énorme onde de choc. Celle-ci inflige XX pts de dégâts magiques aux champions et aux monstres épiques et ralentit tous les ennemis touchés de XX% pendant 1 sec.
Aurora lance un trait d'énergie maudite dans une direction, infligeant XX pts de dégâts magiques aux ennemis et les maudissant pendant XX sec. Réactivation : Aurora met fin à la malédiction en arrachant une partie de l'esprit de l'ennemi, ce qui inflige jusqu'à XX pts de dégâts magiques aux ennemis traversés en fonction de leurs PV manquants. Les ennemis touchés par plusieurs projectiles subissent 20% des dégâts au-delà du premier. À la fin de la durée, Aurora relance automatiquement la compétence.
Aurora bondit dans une direction. À l'atterrissage, elle pénètre dans le royaume spirituel, ce qui la rend invisible pendant XX sec et lui octroie Passe-royaume , gagnant +XX% de vitesse de déplacement . Participer à l'élimination d'un champion ennemi réinitialise le délai de récupération de cette compétence.
Aurora fait converger les royaumes, envoyant une boule de magie spirituelle qui inflige XX pts de dégâts magiques aux ennemis dans la zone et les ralentit de XX% (diminue en XX sec). Aurora bondit légèrement en arrière après avoir lancé cette compétence.
Aurora bondit dans une direction. À l'atterrissage, elle fait converger les royaumes et envoie une impulsion d'énergie spirituelle qui inflige XX pts de dégâts magiques et ralentit les ennemis touchés de XX% pendant 2 sec. La zone de convergence reste active pendant XX sec, octroyant Passe-royaume à Aurora pendant XX sec, et lui permettant de se téléporter d'un bord à l'autre de la zone. Les ennemis essayant d'entrer ou de sortir de la zone sont ralentis de XX% pendant XX sec. Aurora peut relancer cette compétence pour mettre fin à l'effet plus tôt.
Azir envoie tous ses soldats de sable dans une zone, infligeant XX pts de dégâts magiques aux ennemis qu'ils traversent et les ralentissant de XX% pendant 1 sec.
Azir invoque un soldat de sable pendant XX sec. Quand Azir attaque un ennemi proche d'un soldat de sable , il ordonne à la place à ce soldat de donner un coup de lance vers cet ennemi, infligeant XX pts de dégâts magiques . Cette compétence a XX charges.
Azir s'octroie un bouclier de XX PV pendant XX sec et se rue vers l'un de ses soldats de sable , infligeant XX pts de dégâts magiques aux ennemis qu'il traverse. Si Azir touche un champion ennemi, il s'arrête et gagne une charge de soldat de sable .
Azir invoque un mur de soldats dotés de boucliers qui chargent vers l'avant, repoussant les ennemis et infligeant XX pts de dégâts magiques . Les soldats conservent ensuite leur formation en mur pendant XX sec et empêchent les ennemis de passer.
Bard tire un projectile d'énergie, infligeant XX pts de dégâts magiques aux deux premiers ennemis touchés. La première cible touchée est ralentie de XX% pendant XX sec. Si le projectile touche un deuxième ennemi ou un mur, tous les ennemis touchés sont étourdis pendant XX sec.
Bard crée un sanctuaire de soin qui octroie +XX vitesse de déplacement (le bonus diminue en XX sec) et qui rend au moins XX PV au premier allié qui le ramasse. Le sanctuaire se renforce pour rendre XX PV après XX sec d'existence. Jusqu'à XX sanctuaires peuvent être actifs simultanément. Si un champion ennemi marche sur un sanctuaire, ce dernier est détruit. Cette compétence a XX charges. Sanctuaires actifs : XX / XX.
Bard ouvre un portail à sens unique à travers un obstacle pendant XX sec. Tous les champions peuvent emprunter le portail en cliquant sur l'entrée lorsqu'ils sont à portée.
Bard projette de l'énergie protectrice dans une zone, mettant en stase toutes les unités et tous les bâtiments touchés pendant XX sec.
Bel'Veth se rue dans une direction, infligeant XX pts de dégâts physiques aux ennemis qu'elle traverse. Chaque direction a son propre délai de récupération de XX sec, lequel diminue à mesure que la vitesse d'attaque augmente.
Bel'Veth donne un coup de queue, infligeant XX pts de dégâts magiques , projetant dans les airs les ennemis pendant XX sec et les ralentissant de XX% pendant XX sec. Si Bel'Veth touche un champion, le délai de récupération de Charge du Néant est réinitialisé pour cette direction.
Bel'Veth canalise une tempête de coups autour d'elle. Elle gagne alors +XX% de réduction des dégâts et +XX vol de vie, et elle attaque XX fois en XX sec (le nombre d'attaques augmente avec la vitesse d'attaque ). Chaque attaque frappe l'ennemi qui a le moins de PV, lui infligeant XX - XX pts de dégâts physiques selon les PV manquants de la cible. Lancer une autre compétence ou réactiver cette compétence y met fin prématurément.
 Passive : toutes les deux attaques contre une même cible, Bel'Veth inflige XX pts de dégâts bruts supplémentaires (cumulable à l'infini). Participer à l'élimination de champions et de monstres épiques génère des coraux du Néant. Active : consommer un corail du Néant octroie XX effet Lavande et active la véritable forme de Bel'Veth pendant XX sec. Les coraux du Néant générés par des monstres épiques du Néant augmentent la durée à XX sec et transforment en rémoras du Néant les sbires tués à proximité. Pendant l'incantation, Bel'Veth ralentit les ennemis proches avant d'exploser, infligeant des dégâts bruts équivalents à XX + XX% des PV manquants de la cible . Dans sa véritable forme, Bel'Veth gagne +XX PV max , +XX vitesse de déplacement en dehors des combats, +XX portée d'attaque et +XX% de vitesse d'attaque totale , et Charge du Néant peut traverser les murs.
Blitzcrank tire sa main droite, attirant vers lui le premier ennemi touché et infligeant XX pts de dégâts magiques .
Blitzcrank surcharge ses circuits pour gagner +XX% de vitesse de déplacement (diminuant progressivement) et +XX% de vitesse d'attaque pendant XX sec. Ensuite, Blitzcrank est ralenti de XX% pendant XX sec.
Blitzcrank charge son poing pour que sa prochaine attaque projette dans les airs pendant XX sec et inflige XX pts de dégâts physiques .
 Passive : quand cette compétence est disponible, les poings de Blitzcrank sont chargés d'électricité, ce qui permet à ses attaques de marquer les ennemis. Après un délai de 1 sec, les ennemis marqués sont frappés par des éclairs qui leur infligent XX pts de dégâts magiques . Active : Blitzcrank entre en surcharge, infligeant XX pts de dégâts magiques et réduisant au silence les ennemis proches pendant XX sec. Les boucliers de ces ennemis sont également détruits.
Brand lance une boule de feu qui inflige XX pts de dégâts magiques au premier ennemi touché. Si la cible est en flammes , elle est étourdie pendant XX sec.
Brand crée un pilier de feu, infligeant XX pts de dégâts magiques . Les unités en flammes subissent XX pts de dégâts à la place.
Brand provoque une puissante explosion sur sa cible, infligeant XX pts de dégâts magiques aux unités proches. Si la cible est en flammes , la portée de la dispersion est doublée.
Brand libère un torrent de flammes qui rebondit jusqu'à 5 fois sur lui ou un ennemi, infligeant XX pts de dégâts magiques aux ennemis touchés. Les rebonds visent en priorité les champions affectés par Flammes mais qui n'ont pas atteint le nombre d'effets max. Si la cible est en flammes , elle est brièvement ralentie de XX%.
Braum projette des éclats de glace depuis son bouclier, infligeant XX pts de dégâts magiques au premier ennemi touché et le ralentissant de XX% (la cible retrouve peu à peu sa vitesse normale en XX sec). Applique un effet Coups étourdissants .
Braum bondit vers un champion ou un sbire allié. À l'arrivée, Braum octroie à la cible +XX armure et +XX résistance magique pendant XX sec. Braum s'octroie +XX armure et +XX résistance magique pendant la même durée.

In [93]:
table_champion

,key,name,title,lore,tags,partype
0,266,Aatrox,Épée des Darkin,"Autrefois, Aatrox et ses frères étaient honoré...",Fighter,Puits de sang
1,103,Ahri,Renarde à neuf queues,"Connectée à la magie du royaume spirituel, Ahr...",Mage / Assassin,Mana
2,84,Akali,Assassine rebelle,Ayant abandonné l'Ordre Kinkou et le titre de ...,Assassin,Énergie
3,166,Akshan,Sentinelle rebelle,"Se jouant du danger, Akshan combat le mal sans...",Marksman / Assassin,Mana
4,12,Alistar,Minotaure,Alistar est un guerrier redoutable cherchant à...,Tank / Support,Mana
...,...,...,...,...,...,...
167,221,Zeri,Étincelle de Zaun,Zeri est une jeune femme vive et téméraire ori...,Marksman,Mana
168,115,Ziggs,Expert des Hexplosifs,Amoureux des grosses bombes et des mèches cour...,Mage,Mana
169,26,Zilean,Gardien du Temps,"Naguère puissant mage d'Icathia, Zilean devint...",Support / Mage,Mana
170,142,Zoé,Manifestation du Crépuscule,"Incarnation de l'espièglerie, de l'imagination...",Mage,Mana
171,143,Zyra,Dame aux ronces,Née au cours d'une ancienne catastrophe magiqu...,Mage / Support,Mana

In [94]:
df_merge = pd.merge(table_champ_spells[['key', 'id']], table_champion[['key', 'name']],
                    on='key')
df_merge

     key       id    name
0    266  AatroxQ  Aatrox
1    266  AatroxW  Aatrox
2    266  AatroxE  Aatrox
3    266  AatroxR  Aatrox
4    103    AhriQ    Ahri
..   ...      ...     ...
683  142     ZoeR     Zoé
684  143    ZyraQ    Zyra
685  143    ZyraW    Zyra
686  143    ZyraE    Zyra
687  143    ZyraR    Zyra

[688 rows x 3 columns]

In [103]:
candidate = None
count = 0

for idx,i,j in zip(df_merge.index, df_merge['id'], df_merge['name']):

    if count == 0:
        candidate = j
    
    if j == candidate:
        count += 1
    else:
        candidate = j
        count = 1
    
    if count == 1:
        df_merge.at[idx, 'new_name_spell'] = j + "Q"
    
    elif count == 2:
        df_merge.at[idx, 'new_name_spell'] = j + "W"
    
    elif count == 3:
        df_merge.at[idx, 'new_name_spell'] = j + "E"
    
    elif count == 4:
        df_merge.at[idx, 'new_name_spell'] = j + "R"

In [104]:
df_merge

     key       id    name new_name_spell
0    266  AatroxQ  Aatrox        AatroxQ
1    266  AatroxW  Aatrox        AatroxW
2    266  AatroxE  Aatrox        AatroxE
3    266  AatroxR  Aatrox        AatroxR
4    103    AhriQ    Ahri          AhriQ
..   ...      ...     ...            ...
683  142     ZoeR     Zoé           ZoéR
684  143    ZyraQ    Zyra          ZyraQ
685  143    ZyraW    Zyra          ZyraW
686  143    ZyraE    Zyra          ZyraE
687  143    ZyraR    Zyra          ZyraR

[688 rows x 4 columns]

In [105]:
for i,j,u in zip(df_merge['id'], df_merge['name'], df_merge['new_name_spell']):
    print(f"{i} / {j} / {u}")

AatroxQ / Aatrox / AatroxQ
AatroxW / Aatrox / AatroxW
AatroxE / Aatrox / AatroxE
AatroxR / Aatrox / AatroxR
AhriQ / Ahri / AhriQ
AhriW / Ahri / AhriW
AhriE / Ahri / AhriE
AhriR / Ahri / AhriR
AkaliQ / Akali / AkaliQ
AkaliW / Akali / AkaliW
AkaliE / Akali / AkaliE
AkaliR / Akali / AkaliR
AkshanQ / Akshan / AkshanQ
AkshanW / Akshan / AkshanW
AkshanE / Akshan / AkshanE
AkshanR / Akshan / AkshanR
Pulverize / Alistar / AlistarQ
Headbutt / Alistar / AlistarW
AlistarE / Alistar / AlistarE
FerociousHowl / Alistar / AlistarR
AmbessaQ / Ambessa / AmbessaQ
AmbessaW / Ambessa / AmbessaW
AmbessaE / Ambessa / AmbessaE
AmbessaR / Ambessa / AmbessaR
BandageToss / Amumu / AmumuQ
AuraofDespair / Amumu / AmumuW
Tantrum / Amumu / AmumuE
CurseoftheSadMummy / Amumu / AmumuR
FlashFrost / Anivia / AniviaQ
Crystallize / Anivia / AniviaW
Frostbite / Anivia / AniviaE
GlacialStorm / Anivia / AniviaR
AnnieQ / Annie / AnnieQ
AnnieW / Annie / AnnieW
AnnieE / Annie / AnnieE
AnnieR / Annie / AnnieR
ApheliosQ / Aphelios / ApheliosQ
ApheliosW / Aphelios / ApheliosW
ApheliosE / Aphelios / ApheliosE
ApheliosR / Aphelios / ApheliosR
AsheQ / Ashe / AsheQ
Volley / Ashe / AsheW
AsheSpiritOfTheHawk / Ashe / AsheE
EnchantedCrystalArrow / Ashe / AsheR
AurelionSolQ / Aurelion Sol / Aurelion SolQ
AurelionSolW / Aurelion Sol / Aurelion SolW
AurelionSolE / Aurelion Sol / Aurelion SolE
AurelionSolR / Aurelion Sol / Aurelion SolR
AuroraQ / Aurora / AuroraQ
AuroraW / Aurora / AuroraW
AuroraE / Aurora / AuroraE
AuroraR / Aurora / AuroraR
AzirQ / Azir / AzirQ
AzirW / Azir / AzirW
AzirE / Azir / AzirE
AzirR / Azir / AzirR
BardQ / Bard / BardQ
BardW / Bard / BardW
BardE / Bard / BardE
BardR / Bard / BardR
BelvethQ / Bel'Veth / Bel'VethQ
BelvethW / Bel'Veth / Bel'VethW
BelvethE / Bel'Veth / Bel'VethE
BelvethR / Bel'Veth / Bel'VethR
RocketGrab / Blitzcrank / BlitzcrankQ
Overdrive / Blitzcrank / BlitzcrankW
PowerFist / Blitzcrank / BlitzcrankE
StaticField / Blitzcrank / BlitzcrankR
BrandQ / Brand / BrandQ
BrandW / Brand / BrandW
BrandE / Brand / BrandE
BrandR / Brand / BrandR
BraumQ / Braum / BraumQ
BraumW / Braum / BraumW
BraumE / Braum / BraumE
BraumR / Braum / BraumR
BriarQ / Briar / BriarQ
BriarW / Briar / BriarW
BriarE / Briar / BriarE
BriarR / Briar / BriarR
CaitlynQ / Caitlyn / CaitlynQ
CaitlynW / Caitlyn / CaitlynW
CaitlynE / Caitlyn / CaitlynE
CaitlynR / Caitlyn / CaitlynR
CamilleQ / Camille / CamilleQ
CamilleW / Camille / CamilleW
CamilleE / Camille / CamilleE
CamilleR / Camille / CamilleR
CassiopeiaQ / Cassiopeia / CassiopeiaQ
CassiopeiaW / Cassiopeia / CassiopeiaW
CassiopeiaE / Cassiopeia / CassiopeiaE
CassiopeiaR / Cassiopeia / CassiopeiaR
Rupture / Cho'Gath / Cho'GathQ
FeralScream / Cho'Gath / Cho'GathW
VorpalSpikes / Cho'Gath / Cho'GathE
Feast / Cho'Gath / Cho'GathR
PhosphorusBomb / Corki / CorkiQ
CarpetBomb / Corki / CorkiW
GGun / Corki / CorkiE
MissileBarrage / Corki / CorkiR
DariusCleave / Darius / DariusQ
DariusNoxianTacticsONH / Darius / DariusW
DariusAxeGrabCone / Darius / DariusE
DariusExecute / Darius / DariusR
DianaQ / Diana / DianaQ
DianaOrbs / Diana / DianaW
DianaTeleport / Diana / DianaE
DianaR / Diana / DianaR
DravenSpinning / Draven / DravenQ
DravenFury / Draven / DravenW
DravenDoubleShot / Draven / DravenE
DravenRCast / Draven / DravenR
DrMundoQ / Dr. Mundo / Dr. MundoQ
DrMundoW / Dr. Mundo / Dr. MundoW
DrMundoE / Dr. Mundo / Dr. MundoE
DrMundoR / Dr. Mundo / Dr. MundoR
EkkoQ / Ekko / EkkoQ
EkkoW / Ekko / EkkoW
EkkoE / Ekko / EkkoE
EkkoR / Ekko / EkkoR
EliseHumanQ / Elise / EliseQ
EliseHumanW / Elise / EliseW
EliseHumanE / Elise / EliseE
EliseR / Elise / EliseR
EvelynnQ / Evelynn / EvelynnQ
EvelynnW / Evelynn / EvelynnW
EvelynnE / Evelynn / EvelynnE
EvelynnR / Evelynn / EvelynnR
EzrealQ / Ezreal / EzrealQ
EzrealW / Ezreal / EzrealW
EzrealE / Ezreal / EzrealE
EzrealR / Ezreal / EzrealR
FiddleSticksQ / Fiddlesticks / FiddlesticksQ
FiddleSticksW / Fiddlesticks / FiddlesticksW
FiddleSticksE / Fiddlesticks / FiddlesticksE
FiddleSticksR / Fiddlesticks / FiddlesticksR
FioraQ / Fiora / FioraQ
FioraW / Fiora / FioraW
FioraE / Fiora / FioraE
FioraR / Fiora / FioraR
FizzQ / Fizz / FizzQ
FizzW / Fizz / FizzW
FizzE / Fizz / FizzE
FizzR / Fizz / FizzR
GalioQ / Galio / GalioQ
GalioW / Galio / GalioW
GalioE / Galio / GalioE
GalioR / Galio / GalioR
GangplankQ / Gangplank / GangplankQ
GangplankW / Gangplank / GangplankW
GangplankE / Gangplank / GangplankE
GangplankR / Gangplank / GangplankR
GarenQ / Garen / GarenQ
GarenW / Garen / GarenW
GarenE / Garen / GarenE
GarenR / Garen / GarenR
GnarQ / Gnar / GnarQ
GnarW / Gnar / GnarW
GnarE / Gnar / GnarE
GnarR / Gnar / GnarR
GragasQ / Gragas / GragasQ
GragasW / Gragas / GragasW
GragasE / Gragas / GragasE
GragasR / Gragas / GragasR
GravesQLineSpell / Graves / GravesQ
GravesSmokeGrenade / Graves / GravesW
GravesMove / Graves / GravesE
GravesChargeShot / Graves / GravesR
GwenQ / Gwen / GwenQ
GwenW / Gwen / GwenW
GwenE / Gwen / GwenE
GwenR / Gwen / GwenR
HecarimRapidSlash / Hecarim / HecarimQ
HecarimW / Hecarim / HecarimW
HecarimRamp / Hecarim / HecarimE
HecarimUlt / Hecarim / HecarimR
HeimerdingerQ / Heimerdinger / HeimerdingerQ
HeimerdingerW / Heimerdinger / HeimerdingerW
HeimerdingerE / Heimerdinger / HeimerdingerE
HeimerdingerR / Heimerdinger / HeimerdingerR
HweiQ / Hwei / HweiQ
HweiW / Hwei / HweiW
HweiE / Hwei / HweiE
HweiR / Hwei / HweiR
IllaoiQ / Illaoi / IllaoiQ
IllaoiW / Illaoi / IllaoiW
IllaoiE / Illaoi / IllaoiE
IllaoiR / Illaoi / IllaoiR
IreliaQ / Irelia / IreliaQ
IreliaW / Irelia / IreliaW
IreliaE / Irelia / IreliaE
IreliaR / Irelia / IreliaR
IvernQ / Ivern / IvernQ
IvernW / Ivern / IvernW
IvernE / Ivern / IvernE
IvernR / Ivern / IvernR
HowlingGale / Janna / JannaQ
SowTheWind / Janna / JannaW
EyeOfTheStorm / Janna / JannaE
ReapTheWhirlwind / Janna / JannaR
JarvanIVDragonStrike / Jarvan IV / Jarvan IVQ
JarvanIVGoldenAegis / Jarvan IV / Jarvan IVW
JarvanIVDemacianStandard / Jarvan IV / Jarvan IVE
JarvanIVCataclysm / Jarvan IV / Jarvan IVR
JaxQ / Jax / JaxQ
JaxW / Jax / JaxW
JaxE / Jax / JaxE
JaxR / Jax / JaxR
JayceToTheSkies / Jayce / JayceQ
JayceStaticField / Jayce / JayceW
JayceThunderingBlow / Jayce / JayceE
JayceStanceHtG / Jayce / JayceR
JhinQ / Jhin / JhinQ
JhinW / Jhin / JhinW
JhinE / Jhin / JhinE
JhinR / Jhin / JhinR
JinxQ / Jinx / JinxQ
JinxW / Jinx / JinxW
JinxE / Jinx / JinxE
JinxR / Jinx / JinxR
KaisaQ / Kai'Sa / Kai'SaQ
KaisaW / Kai'Sa / Kai'SaW
KaisaE / Kai'Sa / Kai'SaE
KaisaR / Kai'Sa / Kai'SaR
KalistaMysticShot / Kalista / KalistaQ
KalistaW / Kalista / KalistaW
KalistaExpunge / Kalista / KalistaE
KalistaRx / Kalista / KalistaR
KarmaQ / Karma / KarmaQ
KarmaSpiritBind / Karma / KarmaW
KarmaSolKimShield / Karma / KarmaE
KarmaMantra / Karma / KarmaR
KarthusLayWasteA1 / Karthus / KarthusQ
KarthusWallOfPain / Karthus / KarthusW
KarthusDefile / Karthus / KarthusE
KarthusFallenOne / Karthus / KarthusR
NullLance / Kassadin / KassadinQ
NetherBlade / Kassadin / KassadinW
ForcePulse / Kassadin / KassadinE
RiftWalk / Kassadin / KassadinR
KatarinaQ / Katarina / KatarinaQ
KatarinaW / Katarina / KatarinaW
KatarinaE / Katarina / KatarinaE
KatarinaR / Katarina / KatarinaR
KayleQ / Kayle / KayleQ
KayleW / Kayle / KayleW
KayleE / Kayle / KayleE
KayleR / Kayle / KayleR
KaynQ / Kayn / KaynQ
KaynW / Kayn / KaynW
KaynE / Kayn / KaynE
KaynR / Kayn / KaynR
KennenShurikenHurlMissile1 / Kennen / KennenQ
KennenBringTheLight / Kennen / KennenW
KennenLightningRush / Kennen / KennenE
KennenShurikenStorm / Kennen / KennenR
KhazixQ / Kha'Zix / Kha'ZixQ
KhazixW / Kha'Zix / Kha'ZixW
KhazixE / Kha'Zix / Kha'ZixE
KhazixR / Kha'Zix / Kha'ZixR
KindredQ / Kindred / KindredQ
KindredW / Kindred / KindredW
KindredE / Kindred / KindredE
KindredR / Kindred / KindredR
KledQ / Kled / KledQ
KledW / Kled / KledW
KledE / Kled / KledE
KledR / Kled / KledR
KogMawQ / Kog'Maw / Kog'MawQ
KogMawBioArcaneBarrage / Kog'Maw / Kog'MawW
KogMawVoidOoze / Kog'Maw / Kog'MawE
KogMawLivingArtillery / Kog'Maw / Kog'MawR
KSanteQ / K'Santé / K'SantéQ
KSanteW / K'Santé / K'SantéW
KSanteE / K'Santé / K'SantéE
KSanteR / K'Santé / K'SantéR
LeblancQ / LeBlanc / LeBlancQ
LeblancW / LeBlanc / LeBlancW
LeblancE / LeBlanc / LeBlancE
LeblancR / LeBlanc / LeBlancR
LeeSinQOne / Lee Sin / Lee SinQ
LeeSinWOne / Lee Sin / Lee SinW
LeeSinEOne / Lee Sin / Lee SinE
LeeSinR / Lee Sin / Lee SinR
LeonaShieldOfDaybreak / Leona / LeonaQ
LeonaSolarBarrier / Leona / LeonaW
LeonaZenithBlade / Leona / LeonaE
LeonaSolarFlare / Leona / LeonaR
LilliaQ / Lillia / LilliaQ
LilliaW / Lillia / LilliaW
LilliaE / Lillia / LilliaE
LilliaR / Lillia / LilliaR
LissandraQ / Lissandra / LissandraQ
LissandraW / Lissandra / LissandraW
LissandraE / Lissandra / LissandraE
LissandraR / Lissandra / LissandraR
LucianQ / Lucian / LucianQ
LucianW / Lucian / LucianW
LucianE / Lucian / LucianE
LucianR / Lucian / LucianR
LuluQ / Lulu / LuluQ
LuluW / Lulu / LuluW
LuluE / Lulu / LuluE
LuluR / Lulu / LuluR
LuxLightBinding / Lux / LuxQ
LuxPrismaticWave / Lux / LuxW
LuxLightStrikeKugel / Lux / LuxE
LuxR / Lux / LuxR
SeismicShard / Malphite / MalphiteQ
Obduracy / Malphite / MalphiteW
Landslide / Malphite / MalphiteE
UFSlash / Malphite / MalphiteR
MalzaharQ / Malzahar / MalzaharQ
MalzaharW / Malzahar / MalzaharW
MalzaharE / Malzahar / MalzaharE
MalzaharR / Malzahar / MalzaharR
MaokaiQ / Maokai / MaokaiQ
MaokaiW / Maokai / MaokaiW
MaokaiE / Maokai / MaokaiE
MaokaiR / Maokai / MaokaiR
AlphaStrike / Maître Yi / Maître YiQ
Meditate / Maître Yi / Maître YiW
WujuStyle / Maître Yi / Maître YiE
Highlander / Maître Yi / Maître YiR
MelQ / Mel / MelQ
MelW / Mel / MelW
MelE / Mel / MelE
MelR / Mel / MelR
MilioQ / Milio / MilioQ
MilioW / Milio / MilioW
MilioE / Milio / MilioE
MilioR / Milio / MilioR
MissFortuneRicochetShot / Miss Fortune / Miss FortuneQ
MissFortuneViciousStrikes / Miss Fortune / Miss FortuneW
MissFortuneScattershot / Miss Fortune / Miss FortuneE
MissFortuneBulletTime / Miss Fortune / Miss FortuneR
MonkeyKingDoubleAttack / Wukong / WukongQ
MonkeyKingDecoy / Wukong / WukongW
MonkeyKingNimbus / Wukong / WukongE
MonkeyKingSpinToWin / Wukong / WukongR
MordekaiserQ / Mordekaiser / MordekaiserQ
MordekaiserW / Mordekaiser / MordekaiserW
MordekaiserE / Mordekaiser / MordekaiserE
MordekaiserR / Mordekaiser / MordekaiserR
MorganaQ / Morgana / MorganaQ
MorganaW / Morgana / MorganaW
MorganaE / Morgana / MorganaE
MorganaR / Morgana / MorganaR
NaafiriQ / Naafiri / NaafiriQ
NaafiriR / Naafiri / NaafiriW
NaafiriE / Naafiri / NaafiriE
NaafiriW / Naafiri / NaafiriR
NamiQ / Nami / NamiQ
NamiW / Nami / NamiW
NamiE / Nami / NamiE
NamiR / Nami / NamiR
NasusQ / Nasus / NasusQ
NasusW / Nasus / NasusW
NasusE / Nasus / NasusE
NasusR / Nasus / NasusR
NautilusAnchorDrag / Nautilus / NautilusQ
NautilusPiercingGaze / Nautilus / NautilusW
NautilusSplashZone / Nautilus / NautilusE
NautilusGrandLine / Nautilus / NautilusR
NeekoQ / Neeko / NeekoQ
NeekoW / Neeko / NeekoW
NeekoE / Neeko / NeekoE
NeekoR / Neeko / NeekoR
JavelinToss / Nidalee / NidaleeQ
Bushwhack / Nidalee / NidaleeW
PrimalSurge / Nidalee / NidaleeE
AspectOfTheCougar / Nidalee / NidaleeR
NilahQ / Nilah / NilahQ
NilahW / Nilah / NilahW
NilahE / Nilah / NilahE
NilahR / Nilah / NilahR
NocturneDuskbringer / Nocturne / NocturneQ
NocturneShroudofDarkness / Nocturne / NocturneW
NocturneUnspeakableHorror / Nocturne / NocturneE
NocturneParanoia / Nocturne / NocturneR
NunuQ / Nunu et Willump / Nunu et WillumpQ
NunuW / Nunu et Willump / Nunu et WillumpW
NunuE / Nunu et Willump / Nunu et WillumpE
NunuR / Nunu et Willump / Nunu et WillumpR
OlafAxeThrowCast / Olaf / OlafQ
OlafFrenziedStrikes / Olaf / OlafW
OlafRecklessStrike / Olaf / OlafE
OlafRagnarok / Olaf / OlafR
OrianaIzunaCommand / Orianna / OriannaQ
OrianaDissonanceCommand / Orianna / OriannaW
OrianaRedactCommand / Orianna / OriannaE
OrianaDetonateCommand / Orianna / OriannaR
OrnnQ / Ornn / OrnnQ
OrnnW / Ornn / OrnnW
OrnnE / Ornn / OrnnE
OrnnR / Ornn / OrnnR
PantheonQ / Pantheon / PantheonQ
PantheonW / Pantheon / PantheonW
PantheonE / Pantheon / PantheonE
PantheonR / Pantheon / PantheonR
PoppyQ / Poppy / PoppyQ
PoppyW / Poppy / PoppyW
PoppyE / Poppy / PoppyE
PoppyR / Poppy / PoppyR
PykeQ / Pyke / PykeQ
PykeW / Pyke / PykeW
PykeE / Pyke / PykeE
PykeR / Pyke / PykeR
QiyanaQ / Qiyana / QiyanaQ
QiyanaW / Qiyana / QiyanaW
QiyanaE / Qiyana / QiyanaE
QiyanaR / Qiyana / QiyanaR
QuinnQ / Quinn / QuinnQ
QuinnW / Quinn / QuinnW
QuinnE / Quinn / QuinnE
QuinnR / Quinn / QuinnR
RakanQ / Rakan / RakanQ
RakanW / Rakan / RakanW
RakanE / Rakan / RakanE
RakanR / Rakan / RakanR
PowerBall / Rammus / RammusQ
DefensiveBallCurl / Rammus / RammusW
PuncturingTaunt / Rammus / RammusE
Tremors2 / Rammus / RammusR
RekSaiQ / Rek'Sai / Rek'SaiQ
RekSaiW / Rek'Sai / Rek'SaiW
RekSaiE / Rek'Sai / Rek'SaiE
RekSaiR / Rek'Sai / Rek'SaiR
RellQ / Rell / RellQ
RellW_Dismount / Rell / RellW
RellE / Rell / RellE
RellR / Rell / RellR
RenataQ / Renata Glasc / Renata GlascQ
RenataW / Renata Glasc / Renata GlascW
RenataE / Renata Glasc / Renata GlascE
RenataR / Renata Glasc / Renata GlascR
RenektonCleave / Renekton / RenektonQ
RenektonPreExecute / Renekton / RenektonW
RenektonSliceAndDice / Renekton / RenektonE
RenektonReignOfTheTyrant / Renekton / RenektonR
RengarQ / Rengar / RengarQ
RengarW / Rengar / RengarW
RengarE / Rengar / RengarE
RengarR / Rengar / RengarR
RivenTriCleave / Riven / RivenQ
RivenMartyr / Riven / RivenW
RivenFeint / Riven / RivenE
RivenFengShuiEngine / Riven / RivenR
RumbleFlameThrower / Rumble / RumbleQ
RumbleShield / Rumble / RumbleW
RumbleGrenade / Rumble / RumbleE
RumbleCarpetBomb / Rumble / RumbleR
RyzeQ / Ryze / RyzeQ
RyzeW / Ryze / RyzeW
RyzeE / Ryze / RyzeE
RyzeR / Ryze / RyzeR
SamiraQ / Samira / SamiraQ
SamiraW / Samira / SamiraW
SamiraE / Samira / SamiraE
SamiraR / Samira / SamiraR
SejuaniQ / Sejuani / SejuaniQ
SejuaniW / Sejuani / SejuaniW
SejuaniE / Sejuani / SejuaniE
SejuaniR / Sejuani / SejuaniR
SennaQ / Senna / SennaQ
SennaW / Senna / SennaW
SennaE / Senna / SennaE
SennaR / Senna / SennaR
SeraphineQ / Séraphine / SéraphineQ
SeraphineW / Séraphine / SéraphineW
SeraphineE / Séraphine / SéraphineE
SeraphineR / Séraphine / SéraphineR
SettQ / Sett / SettQ
SettW / Sett / SettW
SettE / Sett / SettE
SettR / Sett / SettR
Deceive / Shaco / ShacoQ
JackInTheBox / Shaco / ShacoW
TwoShivPoison / Shaco / ShacoE
HallucinateFull / Shaco / ShacoR
ShenQ / Shen / ShenQ
ShenW / Shen / ShenW
ShenE / Shen / ShenE
ShenR / Shen / ShenR
ShyvanaDoubleAttack / Shyvana / ShyvanaQ
ShyvanaImmolationAura / Shyvana / ShyvanaW
ShyvanaFireball / Shyvana / ShyvanaE
ShyvanaTransformCast / Shyvana / ShyvanaR
PoisonTrail / Singed / SingedQ
MegaAdhesive / Singed / SingedW
Fling / Singed / SingedE
InsanityPotion / Singed / SingedR
SionQ / Sion / SionQ
SionW / Sion / SionW
SionE / Sion / SionE
SionR / Sion / SionR
SivirQ / Sivir / SivirQ
SivirW / Sivir / SivirW
SivirE / Sivir / SivirE
SivirR / Sivir / SivirR
SkarnerQ / Skarner / SkarnerQ
SkarnerW / Skarner / SkarnerW
SkarnerE / Skarner / SkarnerE
SkarnerR / Skarner / SkarnerR
SmolderQ / Smolder / SmolderQ
SmolderW / Smolder / SmolderW
SmolderE / Smolder / SmolderE
SmolderR / Smolder / SmolderR
SonaQ / Sona / SonaQ
SonaW / Sona / SonaW
SonaE / Sona / SonaE
SonaR / Sona / SonaR
SorakaQ / Soraka / SorakaQ
SorakaW / Soraka / SorakaW
SorakaE / Soraka / SorakaE
SorakaR / Soraka / SorakaR
SwainQ / Swain / SwainQ
SwainW / Swain / SwainW
SwainE / Swain / SwainE
SwainR / Swain / SwainR
SylasQ / Sylas / SylasQ
SylasW / Sylas / SylasW
SylasE / Sylas / SylasE
SylasR / Sylas / SylasR
SyndraQ / Syndra / SyndraQ
SyndraW / Syndra / SyndraW
SyndraE / Syndra / SyndraE
SyndraR / Syndra / SyndraR
TahmKenchQ / Tahm Kench / Tahm KenchQ
TahmKenchW / Tahm Kench / Tahm KenchW
TahmKenchE / Tahm Kench / Tahm KenchE
TahmKenchR / Tahm Kench / Tahm KenchR
TaliyahQ / Taliyah / TaliyahQ
TaliyahWVC / Taliyah / TaliyahW
TaliyahE / Taliyah / TaliyahE
TaliyahR / Taliyah / TaliyahR
TalonQ / Talon / TalonQ
TalonW / Talon / TalonW
TalonE / Talon / TalonE
TalonR / Talon / TalonR
TaricQ / Taric / TaricQ
TaricW / Taric / TaricW
TaricE / Taric / TaricE
TaricR / Taric / TaricR
TeemoQ / Teemo / TeemoQ
TeemoW / Teemo / TeemoW
TeemoE / Teemo / TeemoE
TeemoR / Teemo / TeemoR
ThreshQ / Thresh / ThreshQ
ThreshW / Thresh / ThreshW
ThreshE / Thresh / ThreshE
ThreshRPenta / Thresh / ThreshR
TristanaQ / Tristana / TristanaQ
TristanaW / Tristana / TristanaW
TristanaE / Tristana / TristanaE
TristanaR / Tristana / TristanaR
TrundleTrollSmash / Trundle / TrundleQ
trundledesecrate / Trundle / TrundleW
TrundleCircle / Trundle / TrundleE
TrundlePain / Trundle / TrundleR
TryndamereQ / Tryndamere / TryndamereQ
TryndamereW / Tryndamere / TryndamereW
TryndamereE / Tryndamere / TryndamereE
UndyingRage / Tryndamere / TryndamereR
WildCards / Twisted Fate / Twisted FateQ
PickACard / Twisted Fate / Twisted FateW
CardmasterStack / Twisted Fate / Twisted FateE
Destiny / Twisted Fate / Twisted FateR
TwitchHideInShadows / Twitch / TwitchQ
TwitchVenomCask / Twitch / TwitchW
TwitchExpunge / Twitch / TwitchE
TwitchFullAutomatic / Twitch / TwitchR
UdyrQ / Udyr / UdyrQ
UdyrW / Udyr / UdyrW
UdyrE / Udyr / UdyrE
UdyrR / Udyr / UdyrR
UrgotQ / Urgot / UrgotQ
UrgotW / Urgot / UrgotW
UrgotE / Urgot / UrgotE
UrgotR / Urgot / UrgotR
VarusQ / Varus / VarusQ
VarusW / Varus / VarusW
VarusE / Varus / VarusE
VarusR / Varus / VarusR
VayneTumble / Vayne / VayneQ
VayneSilveredBolts / Vayne / VayneW
VayneCondemn / Vayne / VayneE
VayneInquisition / Vayne / VayneR
VeigarBalefulStrike / Veigar / VeigarQ
VeigarDarkMatter / Veigar / VeigarW
VeigarEventHorizon / Veigar / VeigarE
VeigarR / Veigar / VeigarR
VelkozQ / Vel'Koz / Vel'KozQ
VelkozW / Vel'Koz / Vel'KozW
VelkozE / Vel'Koz / Vel'KozE
VelkozR / Vel'Koz / Vel'KozR
VexQ / Vex / VexQ
VexW / Vex / VexW
VexE / Vex / VexE
VexR / Vex / VexR
ViQ / Vi / ViQ
ViW / Vi / ViW
ViE / Vi / ViE
ViR / Vi / ViR
ViegoQ / Viego / ViegoQ
ViegoW / Viego / ViegoW
ViegoE / Viego / ViegoE
ViegoR / Viego / ViegoR
ViktorQ / Viktor / ViktorQ
ViktorW / Viktor / ViktorW
ViktorE / Viktor / ViktorE
ViktorR / Viktor / ViktorR
VladimirQ / Vladimir / VladimirQ
VladimirSanguinePool / Vladimir / VladimirW
VladimirE / Vladimir / VladimirE
VladimirHemoplague / Vladimir / VladimirR
VolibearQ / Volibear / VolibearQ
VolibearW / Volibear / VolibearW
VolibearE / Volibear / VolibearE
VolibearR / Volibear / VolibearR
WarwickQ / Warwick / WarwickQ
WarwickW / Warwick / WarwickW
WarwickE / Warwick / WarwickE
WarwickR / Warwick / WarwickR
XayahQ / Xayah / XayahQ
XayahW / Xayah / XayahW
XayahE / Xayah / XayahE
XayahR / Xayah / XayahR
XerathArcanopulseChargeUp / Xerath / XerathQ
XerathArcaneBarrage2 / Xerath / XerathW
XerathMageSpear / Xerath / XerathE
XerathLocusOfPower2 / Xerath / XerathR
XinZhaoQ / Xin Zhao / Xin ZhaoQ
XinZhaoW / Xin Zhao / Xin ZhaoW
XinZhaoE / Xin Zhao / Xin ZhaoE
XinZhaoR / Xin Zhao / Xin ZhaoR
YasuoQ1 / Yasuo / YasuoQ
YasuoW / Yasuo / YasuoW
YasuoE / Yasuo / YasuoE
YasuoR / Yasuo / YasuoR
YoneQ / Yone / YoneQ
YoneW / Yone / YoneW
YoneE / Yone / YoneE
YoneR / Yone / YoneR
YorickQ / Yorick / YorickQ
YorickW / Yorick / YorickW
YorickE / Yorick / YorickE
YorickR / Yorick / YorickR
YunaraQ / Yunara / YunaraQ
YunaraW / Yunara / YunaraW
YunaraE / Yunara / YunaraE
YunaraR / Yunara / YunaraR
YuumiQ / Yuumi / YuumiQ
YuumiW / Yuumi / YuumiW
YuumiE / Yuumi / YuumiE
YuumiR / Yuumi / YuumiR
ZaahenQ / Zaahen / ZaahenQ
ZaahenW / Zaahen / ZaahenW
ZaahenE / Zaahen / ZaahenE
ZaahenR / Zaahen / ZaahenR
ZacQ / Zac / ZacQ
ZacW / Zac / ZacW
ZacE / Zac / ZacE
ZacR / Zac / ZacR
ZedQ / Zed / ZedQ
ZedW / Zed / ZedW
ZedE / Zed / ZedE
ZedR / Zed / ZedR
ZeriQ / Zeri / ZeriQ
ZeriW / Zeri / ZeriW
ZeriE / Zeri / ZeriE
ZeriR / Zeri / ZeriR
ZiggsQ / Ziggs / ZiggsQ
ZiggsW / Ziggs / ZiggsW
ZiggsE / Ziggs / ZiggsE
ZiggsR / Ziggs / ZiggsR
ZileanQ / Zilean / ZileanQ
ZileanW / Zilean / ZileanW
TimeWarp / Zilean / ZileanE
ChronoShift / Zilean / ZileanR
ZoeQ / Zoé / ZoéQ
ZoeW / Zoé / ZoéW
ZoeE / Zoé / ZoéE
ZoeR / Zoé / ZoéR
ZyraQ / Zyra / ZyraQ
ZyraW / Zyra / ZyraW
ZyraE / Zyra / ZyraE
ZyraR / Zyra / ZyraR

In [109]:
df_merge_test = pd.merge(table_champ_spells[['key', 'id']], table_champion[['key', 'name']],
                    on='key')
df_merge_test

     key       id    name
0    266  AatroxQ  Aatrox
1    266  AatroxW  Aatrox
2    266  AatroxE  Aatrox
3    266  AatroxR  Aatrox
4    103    AhriQ    Ahri
..   ...      ...     ...
683  142     ZoeR     Zoé
684  143    ZyraQ    Zyra
685  143    ZyraW    Zyra
686  143    ZyraE    Zyra
687  143    ZyraR    Zyra

[688 rows x 3 columns]

In [112]:
letters = ['Q', 'W', 'E', 'R']

# numérotation 0,1,2,3 par groupe de 'name'
df_merge_test['spell_idx'] = df_merge_test.groupby('name').cumcount()
# display(df_merge_test)
# on mappe 0→Q, 1→W, 2→E, 3→R
df_merge_test['new_name_spell'] = df_merge_test['name'] + df_merge_test['spell_idx'].map(lambda x: letters[x])
df_merge_test

     key       id    name  spell_idx new_name_spell
0    266  AatroxQ  Aatrox          0        AatroxQ
1    266  AatroxW  Aatrox          1        AatroxW
2    266  AatroxE  Aatrox          2        AatroxE
3    266  AatroxR  Aatrox          3        AatroxR
4    103    AhriQ    Ahri          0          AhriQ
..   ...      ...     ...        ...            ...
683  142     ZoeR     Zoé          3           ZoéR
684  143    ZyraQ    Zyra          0          ZyraQ
685  143    ZyraW    Zyra          1          ZyraW
686  143    ZyraE    Zyra          2          ZyraE
687  143    ZyraR    Zyra          3          ZyraR

[688 rows x 5 columns]