# League of Legends

## Librairies

In [1]:
import sys
sys.path.append("../")

import requests
import time
import re
from datetime import datetime
import os
from dotenv import load_dotenv
import pandas as pd
import json
from src.keys_data import KeysData, KeysType
load_dotenv()

True

## Extraction

In [2]:
api_key = os.getenv("API_KEY")
# Limit
# 20 requests evry 1 seconds
# 100 requests every 2 minutes

class ExtractPlayerData:

    def get_puuid(self, gameName : str, tagLine : str):
        """Get account by riot id  
        Returns :
        - puuid : Encrypted PUUID. Exact length of 78 characters.
        - gameName : Name of the account
        - tagLine : Indicatif of the account
        """
        api_url = f"https://europe.api.riotgames.com/riot/account/v1/accounts/by-riot-id/{gameName}/{tagLine}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp


    def get_summoner_info(self, puuid : str):
        """Get a summoner general information by PUUID  
        Returns :
        - profileiconId : ID of the summoner icon associated with the summoner.
        - revisionDate : last modification (events : profile icon change, playing tuto, finishing a game, summoner name change).
        - puuid : Encrypted PUUID. Exact length of 78 characters.
        - summonerLevel : Summoner level associated with the summoner.
        """

        api_url = f"https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-puuid/{puuid}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
    

    def get_last_games_ids(self, puuid :str, start : int = 0, count : int = 20):
        """Get a list of match ids by puuid
        Returns :
        - List : List of last matches
        """

        api_url = f"https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/{puuid}/ids?start={start}&count={count}&api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp


    def get_all_games_ids(self, puuid: str, count_per_request: int = 100, delay: float = 1.5) -> list:
        """
        Récupère l'ensemble des IDs de parties d'un joueur via pagination.
        
        Args:
            puuid: Identifiant unique du joueur
            count_per_request: Nombre de résultats par requête (max 100 selon l'API Riot)
            delay: Délai en secondes entre chaque requête (adapter selon votre clé API)
        
        Returns:
            List[str]: Liste complète des IDs de toutes les parties jouées
        """
        all_match_ids = []
        start = 0

        while True:
            api_url = (
                f"https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/"
                f"{puuid}/ids?start={start}&count={count_per_request}&api_key={api_key}"
            )

            try:
                response = requests.get(api_url)

                # Gestion du rate limiting (429)
                if response.status_code == 429:
                    retry_after = int(response.headers.get("Retry-After", 10))
                    print(f"\t-Rate limit atteint. Attente de {retry_after}s...")
                    time.sleep(retry_after)
                    continue  # Rejoue la même requête

                response.raise_for_status()
                batch = response.json()

            except requests.exceptions.RequestException as e:
                print(f"\t-Erreur lors de la requête (start={start}) : {e}")
                break

            if not batch:
                break  # Plus de résultats, pagination terminée

            all_match_ids.extend(batch)
            print(f"\t- {len(all_match_ids)} parties récupérées...")

            # Si le batch est incomplet, c'est la dernière page
            if len(batch) < count_per_request:
                break

            start += count_per_request
            time.sleep(delay)  # Respect du rate limit entre les requêtes

        return all_match_ids


    def get_game_data(self, game_id : str):
        """Get all informations of a match by match id"""

        api_url = f"https://europe.api.riotgames.com/lol/match/v5/matches/{game_id}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
    

    def get_champion_mastery(self, puuid : str):
        """Get all champion mastery entries sorted by number of champion points descending."""

        api_url = f"https://euw1.api.riotgames.com/lol/champion-mastery/v4/champion-masteries/by-puuid/{puuid}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
    

    def get_gamer_queue(self, puuid : str):
        """Get league entries in all queues for a given puuid"""
    
        api_url = f"https://euw1.api.riotgames.com/lol/league/v4/entries/by-puuid/{puuid}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
    

    def get_challenges_info(self, puuid : str):
        """Returns player information with list of all progressed challenges (REST)"""

        api_url = f"https://euw1.api.riotgames.com/lol/challenges/v1/player-data/{puuid}?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp
    
    
    def get_challenges_description(self, challenge_id : int):
        """Returns the description of a challenge"""

        api_url = f"https://euw1.api.riotgames.com/lol/challenges/v1/challenges/{challenge_id}/config?api_key={api_key}"
        resp = requests.get(api_url).json()
        return resp

In [31]:
class TransformPlayerData:

    def __init__(self):
        self.keys_type = KeysType().key_type
        self.keys_unknown = KeysType().key_unknown

    def _dict_to_list_dict(self, dico : dict) -> list[dict]:
        """Ajoute un dico à une liste"""
        return [dico]
    
    def to_dataframe(self, data) -> pd.DataFrame:
        """Convertie des données de forme dict ou list[dict] en dataframe"""
        if type(data) == dict:
            data = self._dict_to_list_dict(data)
        return pd.DataFrame(data)
    
    def drop_col(self, df : pd.DataFrame, cols : list) -> pd.DataFrame:
        """Enlève des colonnes du dataframe"""
        return df.drop(columns=cols)

    def rename_df_cols(self, df : pd.DataFrame, renamer : dict) -> pd.DataFrame:
        """Rename des colonnes avec un dico {old_col_name : new_col_name}"""
        return df.rename(columns=renamer)
    
    def format_timestamp(self, df: pd.DataFrame, cols: list[str]) -> pd.DataFrame:
        """Formatage des colonnes listées en timestamp au format yyyy-mm-dd hh:mm:ss"""
        for col in cols:
            df[col] = pd.to_datetime(df[col], unit="ms", errors='coerce').dt.floor("s")
            df[col] = df[col].replace({pd.NaT: None})
        return df
    
    def add_puuid(self, df : pd.DataFrame, puuid : str) -> pd.DataFrame:
        """Ajoute le puuid du joueur à un dataframe"""
        df['puuid'] = puuid
        return df
    
    def map_catg_with_index(self, df : pd.DataFrame, col_to_map : str, name_map :str, mapper : dict) -> pd.DataFrame:
        """Ajoue une nouvelle colonne en mappant avec un dico de correspondance"""
        df[name_map] = df[col_to_map].map(mapper)
        return df
    
    def drill_down_dico(self, dico: dict, **kwargs):
        result = dico
        for key, value in kwargs.items():
            if isinstance(result, dict) and key in result:
                result = result[key]
            else:
                raise KeyError(f"Key '{key}' not found in dict")
        return result
    
    def add_key(self, dico : dict, new_key_val : dict):
        """Ajoute des pairs {clé : valeur} à un dictionnaire"""
        dico.update(new_key_val)
        return dico
    
    def clean_text(self, txt : str, exp : str, sub : str):
        """Remplace des éléments de texte spécifiques"""
        txt = re.sub(exp, sub, txt)
        return txt
    
    def merge_df(self, df1 : pd.DataFrame, df2 : pd.DataFrame, left_key : list[str], rigth_key : list[str], how : str = 'inner'):
        """Execute une jointure en deux dataframes"""
        df_merge = pd.merge(df1, df2, how=how, left_on=left_key, right_on=rigth_key)
        return df_merge
    
    def sec_to_minsec(self, secondes : int):
        """Convertie des secondes en format minute:secondes"""
        minu = secondes//60
        sec = secondes%60
        txt = f"{minu:02d}:{sec:02d}"
        return txt
    
    def add_underscore(self, col_names: list[str]) -> list[str]:
        """Convertit les noms de colonnes en snake_case (gestion avancée des majuscules)."""
        def camel_to_snake(name: str) -> str:
            s1 = re.sub('(.)([A-Z][a-z]+)', r'\1_\2', name) # Insère _ avant les majuscules précédées de minuscules ou chiffres
            return re.sub('([a-z0-9])([A-Z])', r'\1_\2', s1).lower() # Insère _ avant les majuscules suivies de minuscules
        
        return [camel_to_snake(name) for name in col_names]
    
    def parse_perks(self, perks: dict) -> dict:
        """
        Transforme le bloc 'perks' de l'API Riot Match v5
        en un dictionnaire plat, prêt à intégrer un DataFrame.
        """
        styles = perks["styles"]
        primary = next(s for s in styles if s["description"] == "primaryStyle")
        sub = next(s for s in styles if s["description"] == "subStyle")

        return {
            # Voie principale
            "id_tree_primary":    primary["style"],
            "id_primary_1":      primary["selections"][0]["perk"],
            "id_primary_2":       primary["selections"][1]["perk"],
            "id_primary_3":       primary["selections"][2]["perk"],
            "id_primary_4":       primary["selections"][3]["perk"],               

            # Voie secondaire
            "id_tree_sub":        sub["style"],
            "id_sub_1":           sub["selections"][0]["perk"],
            "id_sub_2":           sub["selections"][1]["perk"]
        }
    
    def parse_bans(self, teams_data) -> list[dict]:
        bans = []
        for i in teams_data:
            current_bans = i['bans']
            for x in current_bans:
                x.pop('pickTurn')
            bans += current_bans
        return bans
    
    def select_columns(self, df_base : pd.DataFrame, champs : list[str]) -> pd.DataFrame:
        """Capture les colonnes en fonction d'une liste"""
        existing = [x for x in champs if x in df_base.columns]
        non_exist = [x for x in champs if x not in df_base.columns]
        df_new = df_base[existing]
        for col in non_exist:
            type_ = self.keys_type.get(col)
            dtype = self.keys_unknown.get(type_)
            df_new[col] = pd.array([pd.NA] * len(df_new), dtype=dtype.dtype)
            print(type_, dtype)
        return df_new

In [32]:
class Pipelines:

    def __init__(self):
        self.extract = ExtractPlayerData()
        self.transfo = TransformPlayerData()
        self.keys_data = KeysData()


    def pipeline_account(self, gameName : str, tagLine : str):
        """Récupération et traitement des données de compte"""

        print(f"- Récupération du puuid du joueur {gameName} (#{tagLine}).")
        df_account = self.extract.get_puuid(gameName=gameName, tagLine=tagLine)
        print(df_account)
        puuid = df_account['puuid']
        df_account = self.transfo.to_dataframe(data=df_account)
        df_account = self.transfo.rename_df_cols(df_account, renamer = {'gameName':'game_name', 'tagLine':'tag_line'})
        return df_account, puuid


    def pipeline_summoner(self, puuid : str) -> pd.DataFrame:
        """Récupération et traitement des données du summoner"""

        print("- Récupération des données du summoner du joueur.")
        df_summoner = self.extract.get_summoner_info(puuid=puuid)
        df_summoner = self.transfo.to_dataframe(data=df_summoner)
        df_summoner = self.transfo.rename_df_cols(df_summoner, renamer = {'profileIconId':'profile_icon_id', 'revisionDate':'last_modif', 'summonerLevel':'summoner_level'})
        df_summoner = self.transfo.format_timestamp(df_summoner, cols=['last_modif'])
        return df_summoner


    def pipeline_challenges(self, puuid : str) -> pd.DataFrame:
        """Récupération et traitement des données de challenges"""

        print("- Récupération des données d'avancement de challenges du joueur.")
        df_challenges = self.extract.get_challenges_info(puuid=puuid)['challenges']
        df_challenges = self.transfo.to_dataframe(df_challenges)
        df_challenges = self.transfo.format_timestamp(df_challenges, cols = ["achievedTime"])
        df_challenges = self.transfo.drop_col(df_challenges, cols=['position','playersInLevel'])
        df_challenges = self.transfo.rename_df_cols(df_challenges, renamer={'challengeId':'challenge_id', 'achievedTime':'achieved_time'})
        df_challenges = self.transfo.map_catg_with_index(df_challenges, col_to_map='level', name_map='level_index', 
                                                    mapper={'NONE' : 0, 'IRON' : 1, 'BRONZE' : 2, 'SILVER' : 3, 'GOLD' : 4, 
                                                            'PLATINUM' : 5, 'DIAMOND' : 6, 'MASTER' : 7, 'GRANDMASTER' : 8, 'CHALLENGER' : 9})
        all_challenge = []
        cnt = 0
        for id in df_challenges['challenge_id']:
            resp = self.extract.get_challenges_description(challenge_id=id)
            chall_id = self.transfo.drill_down_dico(dico=resp, id='id')
            chall_desc = self.transfo.drill_down_dico(dico=resp, localizedNames="localizedNames", fr_FR="fr_FR")
            chall_desc = self.transfo.add_key(dico=chall_desc, new_key_val={'challenge_id':chall_id})
            all_challenge.append(chall_desc)
            cnt += 1
            print(f"\t- Requete challenges envoyées : {cnt}", end='\r')
            time.sleep(1.5)
        
        all_challenge = self.transfo.to_dataframe(all_challenge)
        all_challenge = self.transfo.drop_col(all_challenge, cols=['shortDescription'])
        all_challenge['description'] = [self.transfo.clean_text(txt=x, exp=r"\xa0", sub="") for x in all_challenge['description']]
        all_challenge['name'] = [self.transfo.clean_text(txt=x, exp=r"\xa0", sub="") for x in all_challenge['name']]
        
        df = self.transfo.merge_df(df1=df_challenges, df2=all_challenge, left_key=['challenge_id'], rigth_key=['challenge_id'], how='left')
        df = self.transfo.add_puuid(df, puuid=puuid)
        return df


    def pipeline_champion_mastery(self, puuid : str) -> pd.DataFrame:
        """Récupération et traitement des données de maitrise des champions"""

        print("- Récupération des données de maîtrise de champions du joueur.")
        df_champion_mastery = self.extract.get_champion_mastery(puuid=puuid)
        df_champion_mastery = self.transfo.to_dataframe(df_champion_mastery)
        df_champion_mastery = self.transfo.drop_col(df_champion_mastery, cols=['championPointsSinceLastLevel', 'markRequiredForNextLevel',
                                                                        'tokensEarned', 'championSeasonMilestone', 'milestoneGrades', 
                                                                        'nextSeasonMilestone'])
        df_champion_mastery = self.transfo.format_timestamp(df_champion_mastery, cols = ['lastPlayTime'])
        df_champion_mastery = self.transfo.rename_df_cols(df_champion_mastery, renamer={'championId':'champ_id', 'championLevel':'champ_level',
                                                                                'championPoints':'champ_points', 'lastPlayTime':'last_time_played',
                                                                                'championPointsUntilNextLevel':'points_to_next_level'})
        return df_champion_mastery
    
    
    def pipeline_queue(self, puuid : str) -> pd.DataFrame:
        """Récupération et traitement des données de ranked"""

        print("- Récupération des données de queue (ranked)")
        df_queue = self.extract.get_gamer_queue(puuid=puuid)
        df_queue = self.transfo.to_dataframe(df_queue)
        df_queue = self.transfo.drop_col(df_queue, cols=['veteran', 'inactive', 'freshBlood', 'hotStreak'])
        df_queue = self.transfo.rename_df_cols(df_queue, renamer={'leagueId':'league_id', 'queueType':'queue_type', 'leaguePoints':'league_points'})
        return df_queue
    

    def pipeline_games(self, puuid : str):
        """Récupération et traitement des données de parties"""

        print("- Récupération des données de parties de jeux.")

        df_matchs_info = []
        df_relation_idgame_puuid = []

        list_id_games = self.extract.get_all_games_ids(puuid=puuid)

        for id in list_id_games:
            
            game = self.extract.get_game_data(game_id=id)

            game_info = game['info']
            game_info = {k:v for k,v in game_info.items() if k in self.keys_data.keys_match_info}
            game_info.update({'match_id' : id})

            df_matchs_info.append(game_info)
            
            game_id = game_info['gameId']

            participants = game['info']['participants']

            for participant in participants:
            
                puuid = participant['puuid']

                participant_data = participant
                participant_data = {k:v for k,v in participant_data.items() if k not in self.keys_data.keys_to_reject}
                participant_data.update({'game_id' : game_id})

                participant_challenge = participant['challenges']
                participant_challenge = {k:v for k,v in participant_challenge.items() if k not in self.keys_data.keys_to_reject_challenges}
                participant_challenge.update({'game_id' : game_id, 'puuid' : puuid})

                participant_perks = participant['perks']
                participant_perks = self.transfo.parse_perks(participant_perks)
                participant_perks.update({'game_id' : game_id, 'puuid' : puuid})
            
                df_relation_idgame_puuid.append({'game_id':id, 'puuid':puuid})

        df_matchs_info = self.transfo.to_dataframe(df_matchs_info)
        df_matchs_info.columns = self.transfo.add_underscore(col_names = df_matchs_info.columns)

        return df_matchs_info

In [33]:
def pipeline_new_player(gameName : str, tagLine : str):
    """Insérer un nouveau joueur en base."""
    
    pipe = Pipelines()

    df_account, puuid = pipe.pipeline_account(gameName=gameName, tagLine=tagLine)
    df_summoner = pipe.pipeline_summoner(puuid=puuid)
    df_challenges = pipe.pipeline_challenges(puuid=puuid)
    df_champion_mastery = pipe.pipeline_champion_mastery(puuid=puuid)
    df_queue = pipe.pipeline_queue(puuid=puuid)

    return df_account, df_summoner, df_challenges, df_champion_mastery, df_queue

In [34]:
df_account, df_summoner, df_challenges, df_champion_mastery, df_queue = pipeline_new_player(gameName='SaduSuricate5900', tagLine='47895')
# df_challenges.to_csv(r"C:\Users\najim\Documents\Projets\LeagueOfLegends\data\clean\df_challenges.csv", index=False, encoding='utf-8', header=True)

- Récupération du puuid du joueur SaduSuricate5900 (#47895).
{'puuid': 'uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ', 'gameName': 'SaduSuricate5900', 'tagLine': '47895'}
- Récupération des données du summoner du joueur.
- Récupération des données d'avancement de challenges du joueur.
- Récupération des données de maîtrise de champions du joueur.
- Récupération des données de queue (ranked)

In [38]:
d = {'account':df_account, 'challenges':df_challenges}
z = d['challenges']
z

,challenge_id,percentile,level,value,achieved_time,level_index,description,name,puuid
0,0,0.176,GOLD,5095.0,2026-03-11 22:53:59,4,,CRISTAL,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
1,1,0.091,PLATINUM,1785.0,2026-01-25 15:57:44,5,,IMAGINATION,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
2,2,0.287,SILVER,645.0,2026-03-11 22:53:59,3,,EXPERTISE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
3,3,0.279,SILVER,630.0,2026-03-10 20:32:53,3,,VÉTÉRANCE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
4,4,0.146,GOLD,1430.0,2026-03-19 22:38:25,4,,TRAVAIL D'ÉQUIPE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
...,...,...,...,...,...,...,...,...,...
222,402403,0.293,IRON,11.0,2026-04-03 22:58:39,1,Posez des Balises de contrôle utiles. Pour êtr...,Contrôler les ténèbres,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
223,402400,0.310,SILVER,120.0,2026-02-12 22:22:13,3,Progressez dans les défis du groupe Débrouilla...,Débrouillardise,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
224,402401,0.212,GOLD,234.0,2026-04-01 20:00:19,4,Détruisez des balises.,Fiat nox,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
225,402408,0.332,BRONZE,7491.0,2026-03-14 19:42:50,2,Récupérez des PO de prime à l'élimination de c...,Rends l'argent!,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...
226,402409,0.225,GOLD,1309220.0,2026-03-26 21:34:54,4,Gagnez des PO.,Jour de paye,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...

In [39]:
for z in d:
    print(z)

account
challenges

In [36]:
df_challenges['achieved_time']

0      2026-03-11 22:53:59
1      2026-01-25 15:57:44
2      2026-03-11 22:53:59
3      2026-03-10 20:32:53
4      2026-03-19 22:38:25
              ...
222    2026-04-03 22:58:39
223    2026-02-12 22:22:13
224    2026-04-01 20:00:19
225    2026-03-14 19:42:50
226    2026-03-26 21:34:54
Name: achieved_time, Length: 227, dtype: object

In [26]:
df_challenges_ = TransformPlayerData().format_timestamp(df_challenges, cols=['achieved_time'])

df_challenges_

,challenge_id,percentile,level,value,achieved_time,level_index,description,name,puuid,achieved_time_2
0,0,0.176,GOLD,5095.0,2026-03-11 22:53:59,4,,CRISTAL,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-11 22:53:59
1,1,0.091,PLATINUM,1785.0,2026-01-25 15:57:44,5,,IMAGINATION,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-01-25 15:57:44
2,2,0.287,SILVER,645.0,2026-03-11 22:53:59,3,,EXPERTISE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-11 22:53:59
3,3,0.279,SILVER,630.0,2026-03-10 20:32:53,3,,VÉTÉRANCE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-10 20:32:53
4,4,0.146,GOLD,1430.0,2026-03-19 22:38:25,4,,TRAVAIL D'ÉQUIPE,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-19 22:38:25
...,...,...,...,...,...,...,...,...,...,...
222,402403,0.293,IRON,11.0,2026-04-03 22:58:39,1,Posez des Balises de contrôle utiles. Pour êtr...,Contrôler les ténèbres,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-04-03 22:58:39
223,402400,0.310,SILVER,120.0,2026-02-12 22:22:13,3,Progressez dans les défis du groupe Débrouilla...,Débrouillardise,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-02-12 22:22:13
224,402401,0.212,GOLD,234.0,2026-04-01 20:00:19,4,Détruisez des balises.,Fiat nox,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-04-01 20:00:19
225,402408,0.332,BRONZE,7491.0,2026-03-14 19:42:50,2,Récupérez des PO de prime à l'élimination de c...,Rends l'argent!,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-14 19:42:50
226,402409,0.225,GOLD,1309220.0,2026-03-26 21:34:54,4,Gagnez des PO.,Jour de paye,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,2026-03-26 21:34:54

In [29]:
df_challenges_['achieved_time_2'] = df_challenges_['achieved_time'].replace({pd.NaT: None})
for i in df_challenges_['achieved_time_2']:
    print(i)

2026-03-11 22:53:59
2026-01-25 15:57:44
2026-03-11 22:53:59
2026-03-10 20:32:53
2026-03-19 22:38:25
2026-01-13 22:28:23
2026-01-24 17:38:04
2026-03-13 19:55:08
2026-02-22 16:01:07
2025-12-14 15:09:40
2026-04-01 20:00:19
2026-03-25 21:13:02
2026-03-14 21:30:59
2026-02-22 16:01:07
2026-02-02 21:08:52
2026-03-14 22:06:35
2026-01-23 16:52:42
2026-04-03 21:53:29
2026-03-15 20:08:28
2026-02-13 23:52:13
2026-03-20 20:43:59
2026-04-03 04:04:55
2026-03-08 23:19:13
2026-01-22 18:50:02
2026-03-13 21:33:56
2026-04-12 16:13:00
2026-01-23 16:26:43
2026-03-08 23:19:13
2026-03-23 20:34:44
2026-03-16 21:05:27
2026-01-22 18:50:02
2026-03-23 20:46:45
2026-03-14 19:42:50
2026-03-13 21:33:56
2026-01-23 16:26:43
2026-03-14 20:13:37
2026-03-13 20:14:50
2026-03-11 19:42:15
2026-04-04 20:25:22
2026-03-09 21:52:22
2026-03-06 20:31:57
2026-02-12 22:22:13
2026-03-09 21:16:26
2026-03-20 22:20:39
None
2026-03-14 15:57:11
2026-01-23 16:22:53
2026-03-20 22:32:44
2026-01-23 15:11:48
2026-02-27 20:57:09
None
2025-12-16 20:39:31
None
2026-02-13 22:56:46
2026-03-06 22:11:38
2026-02-28 15:19:26
2026-04-03 22:33:46
2026-01-27 21:42:59
2026-04-03 21:53:29
2026-04-03 21:53:29
2025-12-23 19:42:35
2026-03-08 20:03:25
2025-12-23 20:04:32
2026-02-24 19:08:10
2026-03-20 22:24:34
2025-12-18 19:27:25
2026-03-11 19:34:37
2026-03-08 20:03:25
2026-02-24 19:08:22
2026-03-18 22:25:41
2026-03-18 22:25:41
2026-03-08 21:27:05
2026-03-14 22:06:35
2026-03-21 17:28:38
2026-04-03 22:58:39
2026-03-13 19:55:08
2026-03-09 21:16:26
2026-03-09 21:52:22
2026-03-11 20:49:13
2026-03-20 22:32:44
2026-03-14 21:30:59
2025-12-18 19:44:17
2026-03-21 18:02:54
2025-12-13 17:02:21
2026-03-21 17:28:38
2025-12-16 17:06:00
2026-01-17 17:16:24
2025-12-18 17:26:01
2026-03-14 20:18:09
2026-02-04 17:09:51
2025-12-16 17:03:52
2026-02-05 22:30:18
2026-03-22 21:20:30
2026-02-04 17:09:51
2026-01-13 20:35:24
2026-03-10 20:02:04
2026-01-27 17:38:41
2026-01-27 17:14:39
2026-03-15 20:08:28
None
2026-01-25 00:43:16
2026-02-12 21:17:48
2026-03-09 20:48:26
2026-01-27 17:40:49
2026-03-11 20:40:21
2026-03-08 20:49:24
2026-03-04 21:00:17
2026-04-09 04:07:59
2026-04-04 22:04:16
2026-03-26 22:41:46
2026-02-12 17:55:35
2026-03-19 22:38:25
2026-02-23 22:07:32
2026-04-04 21:43:38
2026-03-19 21:57:12
2026-04-01 20:58:40
2026-04-10 00:03:39
2026-01-23 17:20:45
2026-02-23 22:20:49
2026-02-27 20:33:44
2026-02-24 19:08:10
2026-03-18 22:25:45
2026-01-23 17:20:45
2026-03-13 21:29:05
2026-01-23 15:38:30
2026-02-09 17:18:51
2026-04-01 20:58:40
2026-03-20 22:32:44
2026-02-22 16:01:07
2026-03-14 21:30:59
None
2026-03-09 22:26:36
2026-01-17 17:16:24
2026-02-28 15:36:29
2026-03-20 21:41:50
2026-01-27 23:26:00
2026-01-27 22:51:02
2026-03-25 21:13:02
2026-02-12 21:46:22
2026-03-13 22:57:51
2026-03-20 20:43:59
2026-01-23 16:04:44
2026-03-08 20:49:24
2026-03-13 20:14:50
2026-03-19 21:57:12
2026-01-23 16:22:53
2026-02-28 15:36:29
2026-03-08 21:27:05
2026-02-28 15:19:26
2026-01-27 17:40:49
2026-02-22 16:01:07
2026-03-11 23:03:14
2026-02-13 23:52:13
2026-03-11 23:03:14
None
None
2026-02-10 13:50:48
2026-04-01 20:58:40
2026-03-30 21:15:24
2026-04-01 20:36:12
2026-03-09 21:16:26
2026-04-01 20:00:19
2026-03-10 20:32:53
2026-03-17 22:28:42
2026-03-03 23:17:00
2026-02-20 23:00:19
2026-03-03 22:58:23
2026-01-12 16:25:15
2026-02-28 21:16:23
2025-12-24 21:09:47
2026-03-08 22:00:53
2026-03-13 22:57:51
2026-03-08 22:26:49
2026-03-13 19:55:08
2026-04-03 22:37:55
2026-04-01 20:58:40
2026-04-01 20:36:12
2026-04-09 20:28:07
2026-02-10 14:18:01
2026-02-10 13:50:48
2026-03-13 19:55:08
None
2026-04-03 22:54:31
None
2026-01-19 19:37:16
2026-01-19 20:05:07
None
2026-01-19 23:00:30
2026-04-03 22:37:55
2026-03-19 21:57:12
None
2026-03-22 23:13:33
2026-03-22 22:19:14
2026-03-22 22:39:39
2026-01-24 21:48:00
2026-01-17 18:29:17
2026-01-16 23:30:06
2026-03-11 22:20:58
2026-03-20 21:07:36
2026-03-11 22:53:59
2026-03-05 22:49:20
2026-01-24 17:38:04
2026-01-23 17:20:45
2026-02-05 18:10:44
2026-02-08 15:43:56
2026-03-18 00:31:00
2026-02-14 05:01:20
2026-02-23 22:07:32
2026-01-23 17:08:13
2026-03-13 20:48:49
2026-03-04 21:00:17
2026-03-13 21:29:05
2026-01-27 17:38:41
2026-02-08 20:37:30
2026-04-05 22:12:24
2026-03-08 21:27:05
2026-01-24 19:52:26
2026-04-05 22:41:19
2026-04-07 20:29:28
2026-04-03 23:55:41
2026-03-20 20:43:59
2026-03-14 16:00:53
2026-04-03 22:58:39
2026-02-12 22:22:13
2026-04-01 20:00:19
2026-03-14 19:42:50
2026-03-26 21:34:54

In [6]:
game_ids = ExtractPlayerData().get_last_games_ids(puuid="uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ")
print(game_ids)
game = ExtractPlayerData().get_game_data(game_id=game_ids[0])
print(game)

['EUW1_7815448877', 'EUW1_7813617595', 'EUW1_7813566408', 'EUW1_7812660733', 'EUW1_7811563477', 'EUW1_7811484250', 'EUW1_7810224282', 'EUW1_7809391587', 'EUW1_7809354105', 'EUW1_7809307754', 'EUW1_7809277434', 'EUW1_7809223070', 'EUW1_7808044049', 'EUW1_7806911148', 'EUW1_7806869126', 'EUW1_7806810410', 'EUW1_7804889503', 'EUW1_7799959352', 'EUW1_7799913488', 'EUW1_7799873055']

In [7]:
game

{'metadata': {'dataVersion': '2',
  'matchId': 'EUW1_7815448877',
  'participants': ['nBSuNnvA6cl1YVbLPqiitYHTai4RbqYLkbIWGYjQ9yuRFT1UUtw0LmamaLaQEJt7FFbjbx_JgI-CTQ',
   '3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY94EHC8KGr1TzmQI-v2ECe2-4PCoo49FHQ',
   'uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ',
   '72McagWPeGuuS74L4uRY3UTlshVglJUcOfUoRKGODtdgs5pE8WBgNjxIQBb2KjBd93KHcHln_ICmog',
   'yGGGMcNUaFDozB2Giu53ROgz_kLNA4JFDaqxeayblIcZGPqotcHrQB7lAMrYT5k0TgLVqGY1BBXNvw',
   'NS9PPnXmDOg6Aw56d-44FSCP8QkJdbaQ6prDg_G81xaBmDAPpzwU2Fo63gtaia2Nlr0wpYbVMMd7AQ',
   'y3cTWMf10f8zpCymCkhMy0hWOAGWSDyomDKXiHdF25IeMsD3Ka-o_mbPE_3GVNGIUeAqcqz6t8sS5w',
   'b_3Px2kh-Di8CY_dS7r-ooYTetDt4PLWB5bXrVMo-IEGpeCseZApP8V8vXSx7UNR9UKj3TRt784D7w',
   '1EumFsY7EnHqHrRCAiAl4wbWBJOGzl3doiwWoKZ3GX12H9zI16U8UxClUikjVLvHI87GIWBaI_VKBA',
   '-O-3DP-7gk31YdS47DpCuQulrdZXo4lMU8Eu1PDwBHAIMivtSnFy2g2yzonVBr12t_Ijl0dBpJtHaA']},
 'info': {'endOfGameResult': 'GameComplete',
  'gameCreation': 1775766487315,
  'gameDuration': 1419,
  'gameEndTimestamp': 1775767953128,
  'gameId': 7815448877,
  'gameMode': 'CLASSIC',
  'gameName': 'teambuilder-match-7815448877',
  'gameStartTimestamp': 1775766533823,
  'gameType': 'MATCHED_GAME',
  'gameVersion': '16.7.760.9485',
  'mapId': 11,
  'participants': [{'PlayerBehavior': {'PlayerBehavior_IsHeroInCombat': 0},
    'PlayerScore0': 0,
    'PlayerScore1': 0,
    'PlayerScore10': 0,
    'PlayerScore11': 0,
    'PlayerScore2': 0,
    'PlayerScore3': 0,
    'PlayerScore4': 0,
    'PlayerScore5': 0,
    'PlayerScore6': 0,
    'PlayerScore7': 0,
    'PlayerScore8': 0,
    'PlayerScore9': 0,
    'allInPings': 0,
    'assistMePings': 0,
    'assists': 3,
    'baronKills': 0,
    'basicPings': 0,
    'challenges': {'12AssistStreakCount': 0,
     'HealFromMapSources': 136,
     'InfernalScalePickup': 0,
     'SWARM_DefeatAatrox': 0,
     'SWARM_DefeatBriar': 0,
     'SWARM_DefeatMiniBosses': 0,
     'SWARM_EvolveWeapon': 0,
     'SWARM_Have3Passives': 0,
     'SWARM_KillEnemy': 0,
     'SWARM_PickupGold': 0,
     'SWARM_ReachLevel50': 0,
     'SWARM_Survive15Min': 0,
     'SWARM_WinWith5EvolvedWeapons': 0,
     'abilityUses': 209,
     'acesBefore15Minutes': 0,
     'alliedJungleMonsterKills': 0,
     'baronTakedowns': 0,
     'blastConeOppositeOpponentCount': 0,
     'bountyGold': 0,
     'buffsStolen': 0,
     'completeSupportQuestInTime': 0,
     'controlWardsPlaced': 0,
     'damagePerMinute': 917.9585499290113,
     'damageTakenOnTeamPercentage': 0.144204029585062,
     'dancedWithRiftHerald': 0,
     'deathsByEnemyChamps': 1,
     'dodgeSkillShotsSmallWindow': 1,
     'doubleAces': 0,
     'dragonTakedowns': 0,
     'earlyLaningPhaseGoldExpAdvantage': 0,
     'effectiveHealAndShielding': 0,
     'elderDragonKillsWithOpposingSoul': 0,
     'elderDragonMultikills': 0,
     'enemyChampionImmobilizations': 3,
     'enemyJungleMonsterKills': 2,
     'epicMonsterKillsNearEnemyJungler': 0,
     'epicMonsterKillsWithin30SecondsOfSpawn': 0,
     'epicMonsterSteals': 0,
     'epicMonsterStolenWithoutSmite': 0,
     'firstTurretKilled': 1,
     'firstTurretKilledTime': 794.102508434,
     'fistBumpParticipation': 0,
     'flawlessAces': 2,
     'fullTeamTakedown': 2,
     'gameLength': 1419.640412727,
     'getTakedownsInAllLanesEarlyJungleAsLaner': 0,
     'goldPerMinute': 514.1264100140875,
     'hadOpenNexus': 0,
     'highestChampionDamage': 1,
     'immobilizeAndKillWithAlly': 0,
     'initialBuffCount': 0,
     'initialCrabCount': 0,
     'jungleCsBefore10Minutes': 0,
     'junglerTakedownsNearDamagedEpicMonster': 0,
     'kTurretsDestroyedBeforePlatesFall': 1,
     'kda': 8,
     'killAfterHiddenWithAlly': 0,
     'killParticipation': 0.24242424242424243,
     'killedChampTookFullTeamDamageSurvived': 0,
     'killingSprees': 1,
     'killsNearEnemyTurret': 3,
     'killsOnOtherLanesEarlyJungleAsLaner': 0,
     'killsOnRecentlyHealedByAramPack': 0,
     'killsUnderOwnTurret': 0,
     'killsWithHelpFromEpicMonster': 0,
     'knockEnemyIntoTeamAndKill': 0,
     'landSkillShotsEarlyGame': 2,
     'laneMinionsFirst10Minutes': 66,
     'laningPhaseGoldExpAdvantage': 0,
     'legendaryCount': 0,
     'legendaryItemUsed': [6692, 3071],
     'lostAnInhibitor': 0,
     'maxCsAdvantageOnLaneOpponent': 50,
     'maxKillDeficit': 4,
     'maxLevelLeadLaneOpponent': 2,
     'mejaisFullStackInTime': 0,
     'moreEnemyJungleThanOpponent': 0,
     'multiKillOneSpell': 0,
     'multiTurretRiftHeraldCount': 0,
     'multikills': 1,
     'multikillsAfterAggressiveFlash': 0,
     'outerTurretExecutesBefore10Minutes': 0,
     'outnumberedKills': 0,
     'outnumberedNexusKill': 0,
     'perfectDragonSoulsTaken': 0,
     'perfectGame': 0,
     'pickKillWithAlly': 4,
     'playedChampSelectPosition': 1,
     'poroExplosions': 0,
     'quickCleanse': 0,
     'quickFirstTurret': 0,
     'quickSoloKills': 0,
     'riftHeraldTakedowns': 0,
     'saveAllyFromDeath': 0,
     'scuttleCrabKills': 0,
     'shortestTimeToAceFromFirstTakedown': 15.01934117399992,
     'skillshotsDodged': 16,
     'skillshotsHit': 9,
     'snowballsHit': 0,
     'soloBaronKills': 0,
     'soloKills': 2,
     'soloTurretsLategame': 2,
     'stealthWardsPlaced': 8,
     'survivedSingleDigitHpCount': 0,
     'survivedThreeImmobilizesInFight': 0,
     'takedownOnFirstTurret': 1,
     'takedowns': 8,
     'takedownsAfterGainingLevelAdvantage': 0,
     'takedownsBeforeJungleMinionSpawn': 0,
     'takedownsFirstXMinutes': 1,
     'takedownsInAlcove': 0,
     'takedownsInEnemyFountain': 0,
     'teamBaronKills': 0,
     'teamDamagePercentage': 0.2341822360498576,
     'teamElderDragonKills': 0,
     'teamRiftHeraldKills': 1,
     'tookLargeDamageSurvived': 0,
     'turretPlatesTaken': 21,
     'turretTakedowns': 7,
     'turretsTakenWithRiftHerald': 0,
     'twentyMinionsIn3SecondsCount': 0,
     'twoWardsOneSweeperCount': 0,
     'unseenRecalls': 0,
     'visionScoreAdvantageLaneOpponent': 0.049480438232421875,
     'visionScorePerMinute': 0.6225641684960634,
     'voidMonsterKill': 0,
     'wardTakedowns': 1,
     'wardTakedownsBefore20M': 1,
     'wardsGuarded': 0},
    'champExperience': 15616,
    'champLevel': 16,
    'championId': 83,
    'championName': 'Yorick',
    'championTransform': 0,
    'commandPings': 0,
    'consumablesPurchased': 1,
    'damageDealtToBuildings': 19380,
    'damageDealtToEpicMonsters': 0,
    'damageDealtToObjectives': 19380,
    'damageDealtToTurrets': 19380,
    'damageSelfMitigated': 15856,
    'dangerPings': 0,
    'deaths': 1,
    'detectorWardsPlaced': 0,
    'doubleKills': 1,
    'dragonKills': 0,
    'eligibleForProgression': True,
    'enemyMissingPings': 0,
    'enemyVisionPings': 1,
    'firstBloodAssist': False,
    'firstBloodKill': False,
    'firstTowerAssist': False,
    'firstTowerKill': True,
    'gameEndedInEarlySurrender': False,
    'gameEndedInSurrender': False,
    'getBackPings': 0,
    'goldEarned': 12164,
    'goldSpent': 10850,
    'holdPings': 0,
    'individualPosition': 'TOP',
    'inhibitorKills': 2,
    'inhibitorTakedowns': 2,
    'inhibitorsLost': 0,
    'item0': 6692,
    'item1': 3071,
    'item2': 3076,
    'item3': 3044,
    'item4': 3057,
    'item5': 3047,
    'item6': 3340,
    'itemsPurchased': 21,
    'killingSprees': 1,
    'kills': 5,
    'lane': 'JUNGLE',
    'largestCriticalStrike': 6,
    'largestKillingSpree': 4,
    'largestMultiKill': 2,
    'longestTimeSpentLiving': 993,
    'magicDamageDealt': 29118,
    'magicDamageDealtToChampions': 6769,
    'magicDamageTaken': 3592,
    'missions': {'playerScore0': 0,
     'playerScore1': 0,
     'playerScore2': 0,
     'playerScore3': 0,
     'playerScore4': 0,
     'playerScore5': 0,
     'playerScore6': 0,
     'playerScore7': 0,
     'playerScore8': 0,
     'playerScore9': 0,
     'playerScore10': 0,
     'playerScore11': 0},
    'needVisionPings': 0,
    'neutralMinionsKilled': 4,
    'nexusKills': 1,
    'nexusLost': 0,
    'nexusTakedowns': 1,
    'objectivesStolen': 0,
    'objectivesStolenAssists': 0,
    'onMyWayPings': 0,
    'participantId': 1,
    'pentaKills': 0,
    'perks': {'statPerks': {'defense': 5013, 'flex': 5008, 'offense': 5005},
     'styles': [{'description': 'primaryStyle',
       'selections': [{'perk': 8010, 'var1': 345, 'var2': 0, 'var3': 0},
        {'perk': 9111, 'var1': 693, 'var2': 160, 'var3': 0},
        {'perk': 9103, 'var1': 23, 'var2': 20, 'var3': 0},
        {'perk': 8299, 'var1': 370, 'var2': 0, 'var3': 0}],
       'style': 8000},
      {'description': 'subStyle',
       'selections': [{'perk': 8446, 'var1': 2652, 'var2': 0, 'var3': 0},
        {'perk': 8451, 'var1': 210, 'var2': 0, 'var3': 0}],
       'style': 8400}]},
    'physicalDamageDealt': 104225,
    'physicalDamageDealtToChampions': 14902,
    'physicalDamageTaken': 11268,
    'placement': 0,
    'playerAugment1': 0,
    'playerAugment2': 0,
    'playerAugment3': 0,
    'playerAugment4': 0,
    'playerAugment5': 0,
    'playerAugment6': 0,
    'playerSubteamId': 0,
    'profileIcon': 907,
    'pushPings': 0,
    'puuid': 'nBSuNnvA6cl1YVbLPqiitYHTai4RbqYLkbIWGYjQ9yuRFT1UUtw0LmamaLaQEJt7FFbjbx_JgI-CTQ',
    'quadraKills': 0,
    'retreatPings': 0,
    'riotIdGameName': 'Ossurnar',
    'riotIdTagline': 'EUW',
    'role': 'NONE',
    'roleBoundItem': 1221,
    'sightWardsBoughtInGame': 0,
    'spell1Casts': 146,
    'spell2Casts': 20,
    'spell3Casts': 40,
    'spell4Casts': 3,
    'subteamPlacement': 0,
    'summoner1Casts': 2,
    'summoner1Id': 12,
    'summoner2Casts': 3,
    'summoner2Id': 4,
    'summonerId': 'eFVI45Fqg5dpxMaL8mJIiquPvVVGNX5xWCXNRhMK7R5aPrECvhRoL45TXA',
    'summonerLevel': 281,
    'summonerName': '',
    'teamEarlySurrendered': False,
    'teamId': 100,
    'teamPosition': 'TOP',
    'timeCCingOthers': 8,
    'timePlayed': 1419,
    'totalAllyJungleMinionsKilled': 0,
    'totalDamageDealt': 138929,
    'totalDamageDealtToChampions': 21719,
    'totalDamageShieldedOnTeammates': 0,
    'totalDamageTaken': 16369,
    'totalEnemyJungleMinionsKilled': 2,
    'totalHeal': 6834,
    'totalHealsOnTeammates': 0,
    'totalMinionsKilled': 189,
    'totalTimeCCDealt': 112,
    'totalTimeSpentDead': 16,
    'totalUnitsHealed': 1,
    'tripleKills': 0,
    'trueDamageDealt': 5585,
    'trueDamageDealtToChampions': 48,
    'trueDamageTaken': 1509,
    'turretKills': 5,
    'turretTakedowns': 7,
    'turretsLost': 0,
    'unrealKills': 0,
    'visionClearedPings': 0,
    'visionScore': 14,
    'visionWardsBoughtInGame': 0,
    'wardsKilled': 1,
    'wardsPlaced': 8,
    'win': True},
   {'PlayerBehavior': {'PlayerBehavior_IsHeroInCombat': 0},
    'PlayerScore0': 0,
    'PlayerScore1': 0,
    'PlayerScore10': 0,
    'PlayerScore11': 0,
    'PlayerScore2': 0,
    'PlayerScore3': 0,
    'PlayerScore4': 0,
    'PlayerScore5': 0,
    'PlayerScore6': 0,
    'PlayerScore7': 0,
    'PlayerScore8': 0,
    'PlayerScore9': 0,
    'allInPings': 0,
    'assistMePings': 0,
    'assists': 6,
    'baronKills': 0,
    'basicPings': 0,
    'challenges': {'12AssistStreakCount': 0,
     'HealFromMapSources': 0,
     'InfernalScalePickup': 0,
     'SWARM_DefeatAatrox': 0,
     'SWARM_DefeatBriar': 0,
     'SWARM_DefeatMiniBosses': 0,
     'SWARM_EvolveWeapon': 0,
     'SWARM_Have3Passives': 0,
     'SWARM_KillEnemy': 0,
     'SWARM_PickupGold': 0,
     'SWARM_ReachLevel50': 0,
     'SWARM_Survive15Min': 0,
     'SWARM_WinWith5EvolvedWeapons': 0,
     'abilityUses': 178,
     'acesBefore15Minutes': 0,
     'alliedJungleMonsterKills': 48,
     'baronTakedowns': 0,
     'blastConeOppositeOpponentCount': 0,
     'bountyGold': 261.6829071044922,
     'buffsStolen': 1,
     'completeSupportQuestInTime': 0,
     'controlWardsPlaced': 0,
     'damagePerMinute': 906.2587892177092,
     'damageTakenOnTeamPercentage': 0.19774186835918797,
     'dancedWithRiftHerald': 0,
     'deathsByEnemyChamps': 1,
     'dodgeSkillShotsSmallWindow': 2,
     'doubleAces': 0,
     'dragonTakedowns': 2,
     'earliestDragonTakedown': 867.6177726660001,
     'earlyLaningPhaseGoldExpAdvantage': 0,
     'effectiveHealAndShielding': 0,
     'elderDragonKillsWithOpposingSoul': 0,
     'elderDragonMultikills': 0,
     'enemyChampionImmobilizations': 63,
     'enemyJungleMonsterKills': 13,
     'epicMonsterKillsNearEnemyJungler': 0,
     'epicMonsterKillsWithin30SecondsOfSpawn': 0,
     'epicMonsterSteals': 0,
     'epicMonsterStolenWithoutSmite': 0,
     'fastestLegendary': 912.145173986,
     'firstTurretKilled': 1,
     'firstTurretKilledTime': 794.102508434,
     'fistBumpParticipation': 0,
     'flawlessAces': 2,
     'fullTeamTakedown': 2,
     'gameLength': 1419.640412727,
     'goldPerMinute': 546.0334637740882,
     'hadOpenNexus': 0,
     'immobilizeAndKillWithAlly': 15,
     'initialBuffCount': 2,
     'initialCrabCount': 1,
     'jungleCsBefore10Minutes': 68.00000011920929,
     'junglerKillsEarlyJungle': 0,
     'junglerTakedownsNearDamagedEpicMonster': 1,
     'kTurretsDestroyedBeforePlatesFall': 0,
     'kda': 19,
     'killAfterHiddenWithAlly': 0,
     'killParticipation': 0.5757575757575758,
     'killedChampTookFullTeamDamageSurvived': 0,
     'killingSprees': 2,
     'killsNearEnemyTurret': 6,
     'killsOnLanersEarlyJungleAsJungler': 3,
     'killsOnRecentlyHealedByAramPack': 0,
     'killsUnderOwnTurret': 1,
     'killsWithHelpFromEpicMonster': 1,
     'knockEnemyIntoTeamAndKill': 18,
     'landSkillShotsEarlyGame': 0,
     'laneMinionsFirst10Minutes': 0,
     'laningPhaseGoldExpAdvantage': 0,
     'legendaryCount': 1,
     'legendaryItemUsed': [6610, 3053, 3026],
     'lostAnInhibitor': 0,
     'maxCsAdvantageOnLaneOpponent': 4,
     'maxKillDeficit': 4,
     'maxLevelLeadLaneOpponent': 3,
     'mejaisFullStackInTime': 0,
     'moreEnemyJungleThanOpponent': -55.50000002980232,
     'multiKillOneSpell': 0,
     'multiTurretRiftHeraldCount': 0,
     'multikills': 2,
     'multikillsAfterAggressiveFlash': 0,
     'outerTurretExecutesBefore10Minutes': 0,
     'outnumberedKills': 6,
     'outnumberedNexusKill': 0,
     'perfectDragonSoulsTaken': 0,
     'perfectGame': 0,
     'pickKillWithAlly': 13,
     'playedChampSelectPosition': 1,
     'poroExplosions': 0,
     'quickCleanse': 0,
     'quickFirstTurret': 0,
     'quickSoloKills': 0,
     'riftHeraldTakedowns': 1,
     'saveAllyFromDeath': 0,
     'scuttleCrabKills': 2,
     'shortestTimeToAceFromFirstTakedown': 15.01934117399992,
     'skillshotsDodged': 25,
     'skillshotsHit': 0,
     'snowballsHit': 0,
     'soloBaronKills': 0,
     'soloKills': 3,
     'stealthWardsPlaced': 7,
     'survivedSingleDigitHpCount': 0,
     'survivedThreeImmobilizesInFight': 2,
     'takedownOnFirstTurret': 0,
     'takedowns': 19,
     'takedownsAfterGainingLevelAdvantage': 0,
     'takedownsBeforeJungleMinionSpawn': 0,
     'takedownsFirstXMinutes': 7,
     'takedownsInAlcove': 0,
     'takedownsInEnemyFountain': 0,
     'teamBaronKills': 0,
     'teamDamagePercentage': 0.2311974867658808,
     'teamElderDragonKills': 0,
     'teamRiftHeraldKills': 1,
     'tookLargeDamageSurvived': 0,
     'turretPlatesTaken': 11,
     'turretTakedowns': 4,
     'turretsTakenWithRiftHerald': 0,
     'twentyMinionsIn3SecondsCount': 0,
     'twoWardsOneSweeperCount': 0,
     'unseenRecalls': 0,
     'visionScoreAdvantageLaneOpponent': 1.757206678390503,
     'visionScorePerMinute': 0.73734539963037,
     'voidMonsterKill': 3,
     'wardTakedowns': 0,
     'wardTakedownsBefore20M': 0,
     'wardsGuarded': 0},
    'champExperience': 13089,
    'champLevel': 15,
    'championId': 254,
    'championName': 'Vi',
    'championTransform': 0,
    'commandPings': 2,
    'consumablesPurchased': 0,
    'damageDealtToBuildings': 5045,
    'damageDealtToEpicMonsters': 34282,
    'damageDealtToObjectives': 39328,
    'damageDealtToTurrets': 5045,
    'damageSelfMitigated': 24887,
    'dangerPings': 0,
    'deaths': 1,
    'detectorWardsPlaced': 0,
    'doubleKills': 2,
    'dragonKills': 2,
    'eligibleForProgression': True,
    'enemyMissingPings': 0,
    'enemyVisionPings': 0,
    'firstBloodAssist': False,
    'firstBloodKill': False,
    'firstTowerAssist': False,
    'firstTowerKill': False,
    'gameEndedInEarlySurrender': False,
    'gameEndedInSurrender': False,
    'getBackPings': 0,
    'goldEarned': 12919,
    'goldSpent': 11150,
    'holdPings': 0,
    'individualPosition': 'JUNGLE',
    'inhibitorKills': 0,
    'inhibitorTakedowns': 2,
    'inhibitorsLost': 0,
    'item0': 3053,
    'item1': 6610,
    'item2': 3047,
    'item3': 3026,
    'item4': 0,
    'item5': 0,
    'item6': 3340,
    'itemsPurchased': 12,
    'killingSprees': 2,
    'kills': 13,
    'lane': 'JUNGLE',
    'largestCriticalStrike': 248,
    'largestKillingSpree': 8,
    'largestMultiKill': 2,
    'longestTimeSpentLiving': 919,
    'magicDamageDealt': 0,
    'magicDamageDealtToChampions': 0,
    'magicDamageTaken': 6060,
    'missions': {'playerScore0': 0,
     'playerScore1': 0,
     'playerScore2': 0,
     'playerScore3': 0,
     'playerScore4': 0,
     'playerScore5': 0,
     'playerScore6': 0,
     'playerScore7': 0,
     'playerScore8': 0,
     'playerScore9': 0,
     'playerScore10': 0,
     'playerScore11': 0},
    'needVisionPings': 0,
    'neutralMinionsKilled': 126,
    'nexusKills': 0,
    'nexusLost': 0,
    'nexusTakedowns': 0,
    'objectivesStolen': 0,
    'objectivesStolenAssists': 0,
    'onMyWayPings': 1,
    'participantId': 2,
    'pentaKills': 0,
    'perks': {'statPerks': {'defense': 5001, 'flex': 5008, 'offense': 5005},
     'styles': [{'description': 'primaryStyle',
       'selections': [{'perk': 9923, 'var1': 53, 'var2': 103, 'var3': 0},
        {'perk': 8143, 'var1': 1034, 'var2': 0, 'var3': 0},
        {'perk': 8140, 'var1': 18, 'var2': 0, 'var3': 0},
        {'perk': 8105, 'var1': 40, 'var2': 5, 'var3': 0}],
       'style': 8100},
      {'description': 'subStyle',
       'selections': [{'perk': 9104, 'var1': 11, 'var2': 0, 'var3': 0},
        {'perk': 9111, 'var1': 1793, 'var2': 380, 'var3': 0}],
       'style': 8000}]},
    'physicalDamageDealt': 110143,
    'physicalDamageDealtToChampions': 19459,
    'physicalDamageTaken': 14262,
    'placement': 0,
    'playerAugment1': 0,
    'playerAugment2': 0,
    'playerAugment3': 0,
    'playerAugment4': 0,
    'playerAugment5': 0,
    'playerAugment6': 0,
    'playerSubteamId': 0,
    'profileIcon': 7037,
    'pushPings': 0,
    'puuid': '3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY94EHC8KGr1TzmQI-v2ECe2-4PCoo49FHQ',
    'quadraKills': 0,
    'retreatPings': 1,
    'riotIdGameName': 'jujulepersqpuc',
    'riotIdTagline': 'EUW',
    'role': 'NONE',
    'roleBoundItem': 1209,
    'sightWardsBoughtInGame': 0,
    'spell1Casts': 73,
    'spell2Casts': 0,
    'spell3Casts': 98,
    'spell4Casts': 7,
    'subteamPlacement': 0,
    'summoner1Casts': 15,
    'summoner1Id': 11,
    'summoner2Casts': 4,
    'summoner2Id': 4,
    'summonerId': 'E_5sysaB33pHCmvzMAwex0blEshW2h8aLQ-w8Om2dNHp5ohBBrTIrciSTw',
    'summonerLevel': 97,
    'summonerName': '',
    'teamEarlySurrendered': False,
    'teamId': 100,
    'teamPosition': 'JUNGLE',
    'timeCCingOthers': 34,
    'timePlayed': 1419,
    'totalAllyJungleMinionsKilled': 78,
    'totalDamageDealt': 189262,
    'totalDamageDealtToChampions': 21442,
    'totalDamageShieldedOnTeammates': 0,
    'totalDamageTaken': 22447,
    'totalEnemyJungleMinionsKilled': 18,
    'totalHeal': 10628,
    'totalHealsOnTeammates': 0,
    'totalMinionsKilled': 17,
    'totalTimeCCDealt': 238,
    'totalTimeSpentDead': 35,
    'totalUnitsHealed': 1,
    'tripleKills': 0,
    'trueDamageDealt': 79118,
    'trueDamageDealtToChampions': 1983,
    'trueDamageTaken': 2124,
    'turretKills': 2,
    'turretTakedowns': 4,
    'turretsLost': 0,
    'unrealKills': 0,
    'visionClearedPings': 0,
    'visionScore': 17,
    'visionWardsBoughtInGame': 0,
    'wardsKilled': 0,
    'wardsPlaced': 7,
    'win': True},
   {'PlayerBehavior': {'PlayerBehavior_IsHeroInCombat': 0},
    'PlayerScore0': 0,

In [3]:
def write_json(data):
    with open(r'C:\Users\najim\Documents\Projets\LeagueOfLegends\data\raw\game_data.json', 'w', encoding='utf-8') as fichier:
    # indent=4 ajoute de l'indentation pour la lisibilité
        json.dump(data, fichier, indent=4, ensure_ascii=False)

def read_json(path):
    # Lire un fichier JSON
    with open(path, "r", encoding="utf-8") as f:
        data = json.load(f)
    return data

In [8]:
def treatgamedata():

    keys = KeysData()
    transfo = TransformPlayerData()
    match = read_json(r"C:\Users\najim\Documents\Projets\LeagueOfLegends\data\raw\game_data.json")

    df_participant_data = []
    df_participant_challenge = []
    df_participant_perks = []
    df_game_info = []
    df_relation_idgame_puuid = []

    id = match['metadata']['matchId']
    
    game_info = match['info']
    game_info = {k:v for k,v in game_info.items() if k in keys.keys_match_info}
    game_info.update({'match_id' : id})
    df_game_info.append(game_info)

    bans = transfo.parse_bans(teams_data = match['info']['teams'])
    
    participants = match['info']['participants']

    for participant in participants:
        
        index_position_participant = participants.index(participant)
        puuid = participant['puuid']

        participant_data = participant
        participant_data = {k:v for k,v in participant_data.items() if k not in keys.keys_to_reject}
        participant_data.update({'game_id' : game_info['gameId'], 'championBan' : bans[index_position_participant]['championId']})
        df_participant_data.append(participant_data)

        participant_challenge = participant['challenges']
        participant_challenge = {k:v for k,v in participant_challenge.items() if k not in keys.keys_to_reject_challenges}
        participant_challenge.update({'game_id' : game_info['gameId'], 'player_id' : puuid})
        df_participant_challenge.append(participant_challenge)

        participant_perks = participant['perks']
        participant_perks = transfo.parse_perks(participant_perks)
        participant_perks.update({'game_id' : game_info['gameId'], 'player_id' : puuid})
        df_participant_perks.append(participant_perks)

        print(participant_data)
        print(participant_challenge)
        print(participant_perks)
        print("\n")
        df_relation_idgame_puuid.append({'game_id':id, 'player_id':puuid})

    

    df_participant_data = pd.DataFrame(df_participant_data)
    df_participant_challenge = pd.DataFrame(df_participant_challenge)

    df_all_game_data = transfo.merge_df(df_participant_data, df_participant_challenge,
                                        left_key=['puuid', 'game_id'],
                                        rigth_key=['player_id', 'game_id'],
                                        how='inner')

    df_participant_perks = pd.DataFrame(df_participant_perks)
    df_game_info = pd.DataFrame(df_game_info)
    df_relation_idgame_puuid = pd.DataFrame(df_relation_idgame_puuid)

    table_communication = transfo.select_columns(df_all_game_data, champs=keys.vision_communication)
    table_identite_joueur = transfo.select_columns(df_all_game_data, champs=keys.identite_joueur)
    table_economie_items = transfo.select_columns(df_all_game_data, champs=keys.economie_items)
    table_cc_capacites = transfo.select_columns(df_all_game_data, champs=keys.cc_capacites)
    table_figth = transfo.select_columns(df_all_game_data, champs=keys.combat)
    table_damage = transfo.select_columns(df_all_game_data, champs=keys.degats)
    table_farming = transfo.select_columns(df_all_game_data, champs=keys.jungle_farm)
    table_objective_structures = transfo.select_columns(df_all_game_data, champs=keys.objectifs_structures)
    table_perf_globale = transfo.select_columns(df_all_game_data, champs=keys.performance_globale)

    return [df_game_info, df_participant_perks, df_relation_idgame_puuid, table_communication, 
            table_identite_joueur, table_economie_items, table_cc_capacites, table_figth, 
            table_damage, table_farming, table_objective_structures, 
            table_perf_globale]

In [9]:
df_game_info, df_participant_perks, df_relation_idgame_puuid, table_communication, table_identite_joueur, table_economie_items, table_cc_capacites, table_figth, table_damage, table_farming, table_objective_structures, table_perf_globale= treatgamedata()
# display(game_info)
# display(participant_data)
# display(participant_challenge)
# display(participant_perks)
# display(relation_id_puuid)
# display(participant_all_data)

{'allInPings': 0, 'assistMePings': 0, 'assists': 2, 'baronKills': 0, 'basicPings': 0, 'champExperience': 15255, 'champLevel': 16, 'championId': 39, 'championName': 'Irelia', 'championTransform': 0, 'commandPings': 3, 'consumablesPurchased': 2, 'damageDealtToBuildings': 3553, 'damageDealtToEpicMonsters': 196, 'damageDealtToObjectives': 3750, 'damageDealtToTurrets': 3553, 'damageSelfMitigated': 27429, 'dangerPings': 0, 'deaths': 8, 'detectorWardsPlaced': 0, 'doubleKills': 0, 'dragonKills': 0, 'eligibleForProgression': True, 'enemyMissingPings': 3, 'enemyVisionPings': 0, 'firstBloodAssist': False, 'firstBloodKill': False, 'firstTowerAssist': False, 'firstTowerKill': False, 'gameEndedInEarlySurrender': False, 'gameEndedInSurrender': False, 'getBackPings': 3, 'goldEarned': 10350, 'goldSpent': 9300, 'holdPings': 0, 'individualPosition': 'TOP', 'inhibitorKills': 0, 'inhibitorTakedowns': 0, 'inhibitorsLost': 4, 'item0': 3181, 'item1': 3153, 'item2': 2019, 'item3': 0, 'item4': 3047, 'item5': 2022, 'item6': 3340, 'itemsPurchased': 24, 'killingSprees': 0, 'kills': 3, 'lane': 'JUNGLE', 'largestCriticalStrike': 0, 'largestKillingSpree': 0, 'largestMultiKill': 1, 'longestTimeSpentLiving': 379, 'magicDamageDealt': 16050, 'magicDamageDealtToChampions': 3320, 'magicDamageTaken': 7606, 'needVisionPings': 0, 'neutralMinionsKilled': 0, 'nexusKills': 0, 'nexusLost': 1, 'nexusTakedowns': 0, 'objectivesStolen': 0, 'objectivesStolenAssists': 0, 'onMyWayPings': 3, 'participantId': 1, 'pentaKills': 0, 'physicalDamageDealt': 138082, 'physicalDamageDealtToChampions': 11795, 'physicalDamageTaken': 20355, 'pushPings': 0, 'puuid': 'qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5SJZN0gLjNDBBtTTwsXLVfyqjSZFXFk9Q', 'quadraKills': 0, 'retreatPings': 0, 'riotIdGameName': 'Low Low Coast', 'riotIdTagline': 'TRUMP', 'role': 'NONE', 'roleBoundItem': 1220, 'sightWardsBoughtInGame': 0, 'spell1Casts': 234, 'spell2Casts': 15, 'spell3Casts': 47, 'spell4Casts': 8, 'summoner1Casts': 3, 'summoner1Id': 4, 'summoner2Casts': 6, 'summoner2Id': 14, 'summonerId': 'xUEg1hcTKiJN8yXLSBfFcs-u0aRLl61aPjTlac8ACW4PmYsFzraRLzjRJw', 'summonerLevel': 176, 'summonerName': '', 'teamEarlySurrendered': False, 'teamId': 100, 'teamPosition': 'TOP', 'timeCCingOthers': 10, 'timePlayed': 1604, 'totalAllyJungleMinionsKilled': 0, 'totalDamageDealt': 161312, 'totalDamageDealtToChampions': 16623, 'totalDamageShieldedOnTeammates': 0, 'totalDamageTaken': 32295, 'totalEnemyJungleMinionsKilled': 0, 'totalHeal': 8456, 'totalHealsOnTeammates': 0, 'totalMinionsKilled': 233, 'totalTimeCCDealt': 46, 'totalTimeSpentDead': 296, 'totalUnitsHealed': 1, 'tripleKills': 0, 'trueDamageDealt': 7179, 'trueDamageDealtToChampions': 1508, 'trueDamageTaken': 4332, 'turretKills': 0, 'turretTakedowns': 0, 'turretsLost': 11, 'unrealKills': 0, 'visionClearedPings': 0, 'visionScore': 16, 'visionWardsBoughtInGame': 0, 'wardsKilled': 0, 'wardsPlaced': 7, 'win': False, 'game_id': 7799959352, 'championBan': 121}
{'abilityUses': 304, 'acesBefore15Minutes': 0, 'alliedJungleMonsterKills': 0, 'baronTakedowns': 0, 'blastConeOppositeOpponentCount': 0, 'bountyGold': 437.7174072265625, 'buffsStolen': 0, 'completeSupportQuestInTime': 0, 'controlWardsPlaced': 0, 'damagePerMinute': 621.7319238571899, 'damageTakenOnTeamPercentage': 0.24048936525616926, 'dancedWithRiftHerald': 0, 'deathsByEnemyChamps': 8, 'dodgeSkillShotsSmallWindow': 1, 'doubleAces': 0, 'dragonTakedowns': 0, 'earlyLaningPhaseGoldExpAdvantage': 0, 'effectiveHealAndShielding': 0, 'elderDragonKillsWithOpposingSoul': 0, 'elderDragonMultikills': 0, 'enemyChampionImmobilizations': 12, 'enemyJungleMonsterKills': 0, 'epicMonsterKillsNearEnemyJungler': 0, 'epicMonsterKillsWithin30SecondsOfSpawn': 0, 'epicMonsterSteals': 0, 'epicMonsterStolenWithoutSmite': 0, 'firstTurretKilled': 0, 'fistBumpParticipation': 0, 'flawlessAces': 0, 'fullTeamTakedown': 1, 'getTakedownsInAllLanesEarlyJungleAsLaner': 0, 'goldPerMinute': 387.0955606363761, 'hadOpenNexus': 0, 'immobilizeAndKillWithAlly': 2, 'initialBuffCount': 0, 'initialCrabCount': 0, 'jungleCsBefore10Minutes': 0, 'junglerTakedownsNearDamagedEpicMonster': 0, 'kTurretsDestroyedBeforePlatesFall': 0, 'kda': 0.625, 'killAfterHiddenWithAlly': 0, 'killParticipation': 0.2631578947368421, 'killedChampTookFullTeamDamageSurvived': 0, 'killsNearEnemyTurret': 1, 'killsOnOtherLanesEarlyJungleAsLaner': 0, 'killsUnderOwnTurret': 1, 'killsWithHelpFromEpicMonster': 0, 'knockEnemyIntoTeamAndKill': 0, 'landSkillShotsEarlyGame': 3, 'laneMinionsFirst10Minutes': 83, 'laningPhaseGoldExpAdvantage': 0, 'legendaryCount': 0, 'lostAnInhibitor': 0, 'maxCsAdvantageOnLaneOpponent': 27, 'maxKillDeficit': 0, 'maxLevelLeadLaneOpponent': 1, 'moreEnemyJungleThanOpponent': 0, 'multiKillOneSpell': 0, 'multiTurretRiftHeraldCount': 0, 'multikills': 0, 'multikillsAfterAggressiveFlash': 0, 'outerTurretExecutesBefore10Minutes': 0, 'outnumberedKills': 0, 'outnumberedNexusKill': 0, 'perfectDragonSoulsTaken': 0, 'perfectGame': 0, 'pickKillWithAlly': 4, 'playedChampSelectPosition': 1, 'quickCleanse': 0, 'quickFirstTurret': 0, 'quickSoloKills': 0, 'riftHeraldTakedowns': 0, 'saveAllyFromDeath': 0, 'scuttleCrabKills': 0, 'skillshotsDodged': 23, 'skillshotsHit': 18, 'soloBaronKills': 0, 'soloKills': 1, 'stealthWardsPlaced': 7, 'takedownOnFirstTurret': 0, 'takedowns': 5, 'takedownsAfterGainingLevelAdvantage': 0, 'takedownsBeforeJungleMinionSpawn': 0, 'takedownsFirstXMinutes': 2, 'takedownsInAlcove': 0, 'takedownsInEnemyFountain': 0, 'teamBaronKills': 0, 'teamDamagePercentage': 0.21851445380872853, 'teamElderDragonKills': 0, 'teamRiftHeraldKills': 0, 'turretPlatesTaken': 2, 'turretsTakenWithRiftHerald': 0, 'twoWardsOneSweeperCount': 0, 'visionScoreAdvantageLaneOpponent': -0.00878453254699707, 'visionScorePerMinute': 0.6052313130028022, 'voidMonsterKill': 0, 'wardTakedowns': 0, 'wardTakedownsBefore20M': 0, 'wardsGuarded': 0, 'game_id': 7799959352, 'player_id': 'qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5SJZN0gLjNDBBtTTwsXLVfyqjSZFXFk9Q'}
{'id_tree_primary': 8000, 'id_primary_1': 8010, 'id_primary_2': 9111, 'id_primary_3': 9104, 'id_primary_4': 8299, 'id_tree_sub': 8400, 'id_sub_1': 8473, 'id_sub_2': 8242, 'game_id': 7799959352, 'player_id': 'qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5SJZN0gLjNDBBtTTwsXLVfyqjSZFXFk9Q'}


{'allInPings': 0, 'assistMePings': 0, 'assists': 5, 'baronKills': 0, 'basicPings': 0, 'champExperience': 10022, 'champLevel': 13, 'championId': 254, 'championName': 'Vi', 'championTransform': 0, 'commandPings': 0, 'consumablesPurchased': 0, 'damageDealtToBuildings': 0, 'damageDealtToEpicMonsters': 5819, 'damageDealtToObjectives': 5819, 'damageDealtToTurrets': 0, 'damageSelfMitigated': 24702, 'dangerPings': 0, 'deaths': 11, 'detectorWardsPlaced': 0, 'doubleKills': 0, 'dragonKills': 1, 'eligibleForProgression': True, 'enemyMissingPings': 3, 'enemyVisionPings': 0, 'firstBloodAssist': False, 'firstBloodKill': False, 'firstTowerAssist': False, 'firstTowerKill': False, 'gameEndedInEarlySurrender': False, 'gameEndedInSurrender': False, 'getBackPings': 0, 'goldEarned': 9506, 'goldSpent': 8900, 'holdPings': 0, 'individualPosition': 'JUNGLE', 'inhibitorKills': 0, 'inhibitorTakedowns': 0, 'inhibitorsLost': 4, 'item0': 6676, 'item1': 3158, 'item2': 6692, 'item3': 6670, 'item4': 1036, 'item5': 0, 'item6': 3340, 'itemsPurchased': 13, 'killingSprees': 1, 'kills': 6, 'lane': 'JUNGLE', 'largestCriticalStrike': 454, 'largestKillingSpree': 3, 'largestMultiKill': 1, 'longestTimeSpentLiving': 646, 'magicDamageDealt': 0, 'magicDamageDealtToChampions': 0, 'magicDamageTaken': 9004, 'needVisionPings': 0, 'neutralMinionsKilled': 107, 'nexusKills': 0, 'nexusLost': 1, 'nexusTakedowns': 0, 'objectivesStolen': 0, 'objectivesStolenAssists': 0, 'onMyWayPings': 4, 'participantId': 2, 'pentaKills': 0, 'physicalDamageDealt': 88142, 'physicalDamageDealtToChampions': 12112, 'physicalDamageTaken': 17683, 'pushPings': 0, 'puuid': '3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY94EHC8KGr1TzmQI-v2ECe2-4PCoo49FHQ', 'quadraKills': 0, 'retreatPings': 0, 'riotIdGameName': 'jujulepersqpuc', 'riotIdTagline': 'EUW', 'role': 'NONE', 'roleBoundItem': 1209, 'sightWardsBoughtInGame': 0, 'spell1Casts': 63, 'spell2Casts': 0, 'spell3Casts': 78, 'spell4Casts': 8, 'summoner1Casts': 15, 'summoner1Id': 11, 'summoner2Casts': 4, 'summoner2Id': 4, 'summonerId': 'E_5sysaB33pHCmvzMAwex0blEshW2h8aLQ-w8Om2dNHp5ohBBrTIrciSTw', 'summonerLevel': 94, 'summonerName': '', 'teamEarlySurrendered': False, 'teamId': 100, 'teamPosition': 'JUNGLE', 'timeCCingOthers': 26, 'timePlayed': 1604, 'totalAllyJungleMinionsKilled': 91, 'totalDamageDealt': 128380, 'totalDamageDealtToChampions': 13167, 'totalDamageShieldedOnTeammates': 0, 'totalDamageTaken': 29959, 'totalEnemyJungleMinionsKilled': 2, 'totalHeal': 4968, 'totalHealsOnTeammates': 0, 'totalMinionsKilled': 6, 'totalTimeCCDealt': 185, 'totalTimeSpentDead': 389, 'totalUnitsHealed': 1, 'tripleKills': 0, 'trueDamageDealt': 40237, 'trueDamageDealtToChampions': 1054, 'trueDamageTaken': 3271, 'turretKills': 0, 'turretTakedowns': 0, 'turretsLost': 11, 'unrealKills': 0, 'visionClearedPings': 0, 'visionScore': 19, 'visionWardsBoughtInGame': 0, 'wardsKilled': 0, 'wardsPlaced': 9, 'win': False, 'game_id': 7799959352, 'championBan': 28}
{'abilityUses': 149, 'acesBefore15Minutes': 0, 'alliedJungleMonsterKills': 55, 'baronTakedowns': 0, 'blastConeOppositeOpponentCount': 0, 'bountyGold': 169.44424438476562, 'buffsStolen': 0, 'completeSupportQuestInTime': 0, 'controlWardsPlaced': 0, 'damagePerMinute': 492.46590425291157, 'damageTakenOnTeamPercentage': 0.22309558270583058, 'dancedWithRiftHerald': 0, 'deathsByEnemyChamps': 11, 'dodgeSkillShotsSmallWindow': 1, 'doubleAces': 0, 'dragonTakedowns': 1, 'earliestDragonTakedown': 361.931712893, 'earlyLaningPhaseGoldExpAdvantage': 0, 'effectiveHealAndShielding': 0, 'elderDragonKillsWithOpposingSoul': 0, 'elderDragonMultikills': 0, 'enemyChampionImmobilizations': 57, 'enemyJungleMonsterKills': 2, 'epicMonsterKillsNearEnemyJungler': 1, 'epicMonsterKillsWithin30SecondsOfSpawn': 0, 'epicMonsterSteals': 0, 'epicMonsterStolenWithoutSmite': 0, 'firstTurretKilled': 0, 'fistBumpParticipation': 0, 'flawlessAces': 0, 'fullTeamTakedown': 1, 'goldPerMinute': 355.5350794955026, 'hadOpenNexus': 0, 'immobilizeAndKillWithAlly': 9, 'initialBuffCount': 2, 'initialCrabCount': 1, 'jungleCsBefore10Minutes': 60.000000059604645, 'junglerKillsEarlyJungle': 0, 'junglerTakedownsNearDamagedEpicMonster': 0, 'kTurretsDestroyedBeforePlatesFall': 0, 'kda': 1, 'killAfterHiddenWithAlly': 0, 'killParticipation': 0.5789473684210527, 'killedChampTookFullTeamDamageSurvived': 0, 'killsNearEnemyTurret': 1, 'killsOnLanersEarlyJungleAsJungler': 3, 'killsUnderOwnTurret': 0, 'killsWithHelpFromEpicMonster': 0, 'knockEnemyIntoTeamAndKill': 6, 'landSkillShotsEarlyGame': 0, 'laneMinionsFirst10Minutes': 0, 'laningPhaseGoldExpAdvantage': 0, 'legendaryCount': 0, 'lostAnInhibitor': 0, 'maxCsAdvantageOnLaneOpponent': 4, 'maxKillDeficit': 0, 'maxLevelLeadLaneOpponent': 0, 'moreEnemyJungleThanOpponent': -67.50000008940697, 'multiKillOneSpell': 0, 'multiTurretRiftHeraldCount': 0, 'multikills': 0, 'multikillsAfterAggressiveFlash': 0, 'outerTurretExecutesBefore10Minutes': 0, 'outnumberedKills': 0, 'outnumberedNexusKill': 0, 'perfectDragonSoulsTaken': 0, 'perfectGame': 0, 'pickKillWithAlly': 9, 'playedChampSelectPosition': 1, 'quickCleanse': 0, 'quickFirstTurret': 0, 'quickSoloKills': 0, 'riftHeraldTakedowns': 0, 'saveAllyFromDeath': 0, 'scuttleCrabKills': 1, 'skillshotsDodged': 22, 'skillshotsHit': 0, 'soloBaronKills': 0, 'soloKills': 1, 'stealthWardsPlaced': 9, 'takedownOnFirstTurret': 0, 'takedowns': 11, 'takedownsAfterGainingLevelAdvantage': 0, 'takedownsBeforeJungleMinionSpawn': 0, 'takedownsFirstXMinutes': 6, 'takedownsInAlcove': 0, 'takedownsInEnemyFountain': 0, 'teamBaronKills': 0, 'teamDamagePercentage': 0.17308250382195992, 'teamElderDragonKills': 0, 'teamRiftHeraldKills': 0, 'turretPlatesTaken': 0, 'turretsTakenWithRiftHerald': 0, 'twoWardsOneSweeperCount': 0, 'visionScoreAdvantageLaneOpponent': 0.07144463062286377, 'visionScorePerMinute': 0.7356623295606476, 'voidMonsterKill': 0, 'wardTakedowns': 0, 'wardTakedownsBefore20M': 0, 'wardsGuarded': 0, 'game_id': 7799959352, 'player_id': '3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY94EHC8KGr1TzmQI-v2ECe2-4PCoo49FHQ'}
{'id_tree_primary': 8100, 'id_primary_1': 9923, 'id_primary_2': 8143, 'id_primary_3': 8140, 'id_primary_4': 8105, 'id_tree_sub': 8000, 'id_sub_1': 9104, 'id_sub_2': 9111, 'game_id': 7799959352, 'player_id': '3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY94EHC8KGr1TzmQI-v2ECe2-4PCoo49FHQ'}


{'allInPings': 0, 'assistMePings': 0, 'assists': 7, 'baronKills': 0, 'basicPings': 0, 'champExperience': 13954, 'champLevel': 15, 'championId': 136, 'championName': 'AurelionSol', 'championTransform': 0, 'commandPings': 0, 'consumablesPurchased': 2, 'damageDealtToBuildings': 0, 'damageDealtToEpicMonsters': 486, 'damageDealtToObjectives': 486, 'damageDealtToTurrets': 0, 'damageSelfMitigated': 12291, 'dangerPings': 0, 'deaths': 6, 'detectorWardsPlaced': 0, 'doubleKills': 0, 'dragonKills': 0, 'eligibleForProgression': True, 'enemyMissingPings': 0, 'enemyVisionPings': 0, 'firstBloodAssist': False, 'firstBloodKill': False, 'firstTowerAssist': False, 'firstTowerKill': False, 'gameEndedInEarlySurrender': False, 'gameEndedInSurrender': False, 'getBackPings': 0, 'goldEarned': 7658, 'goldSpent': 7550, 'holdPings': 0, 'individualPosition': 'MIDDLE', 'inhibitorKills': 0, 'inhibitorTakedowns': 0, 'inhibitorsLost': 4, 'item0': 1056, 'item1': 2503, 'item2': 1027, 'item3': 3173, 'item4': 6653, 'item5': 0, 'item6': 3340, 'itemsPurchased': 18, 'killingSprees': 0, 'kills': 0, 'lane': 'MIDDLE', 'largestCriticalStrike': 0, 'largestKillingSpree': 0, 'largestMultiKill': 0, 'longestTimeSpentLiving': 499, 'magicDamageDealt': 114273, 'magicDamageDealtToChampions': 10100, 'magicDamageTaken': 8668, 'needVisionPings': 0, 'neutralMinionsKilled': 0, 'nexusKills': 0, 'nexusLost': 1, 'nexusTakedowns': 0, 'objectivesStolen': 0, 'objectivesStolenAssists': 0, 'onMyWayPings': 0, 'participantId': 3, 'pentaKills': 0, 'physicalDamageDealt': 2768, 'physicalDamageDealtToChampions': 0, 'physicalDamageTaken': 10714, 'pushPings': 0, 'puuid': 'uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ', 'quadraKills': 0, 'retreatPings': 0, 'riotIdGameName': 'SaduSuricate5900', 'riotIdTagline': '47895', 'role': 'SOLO', 'roleBoundItem': 1206, 'sightWardsBoughtInGame': 0, 'spell1Casts': 101, 'spell2Casts': 24, 'spell3Casts': 49, 'spell4Casts': 6, 'summoner1Casts': 2, 'summoner1Id': 4, 'summoner2Casts': 2, 'summoner2Id': 12, 'summonerId': 'iX6zvmMvEbWgmbdBk4zDAiTmvBYkuAO-rJtFFWVwE0FDymq-cepZ0nK_sQ', 'summonerLevel': 88, 'summonerName': '', 'teamEarlySurrendered': False, 'teamId': 100, 'teamPosition': 'MIDDLE', 'timeCCingOthers': 8, 'timePlayed': 1604, 'totalAllyJungleMinionsKilled': 0, 'totalDamageDealt': 120262, 'totalDamageDealtToChampions': 10159, 'totalDamageShieldedOnTeammates': 0, 'totalDamageTaken': 20935, 'totalEnemyJungleMinionsKilled': 0, 'totalHeal': 3248, 'totalHealsOnTeammates': 0, 'totalMinionsKilled': 176, 'totalTimeCCDealt': 66, 'totalTimeSpentDead': 172, 'totalUnitsHealed': 1, 'tripleKills': 0, 'trueDamageDealt': 3220, 'trueDamageDealtToChampions': 58, 'trueDamageTaken': 1552, 'turretKills': 0, 'turretTakedowns': 0, 'turretsLost': 11, 'unrealKills': 0, 'visionClearedPings': 0, 'visionScore': 12, 'visionWardsBoughtInGame': 0, 'wardsKilled': 0, 'wardsPlaced': 7, 'win': False, 'game_id': 7799959352, 'championBan': 99}
{'abilityUses': 180, 'acesBefore15Minutes': 0, 'alliedJungleMonsterKills': 0, 'baronTakedowns': 0, 'blastConeOppositeOpponentCount': 0, 'bountyGold': 0, 'buffsStolen': 0, 'completeSupportQuestInTime': 0, 'controlWardsPlaced': 0, 'damagePerMinute': 379.95275319240375, 'damageTakenOnTeamPercentage': 0.15589951743124109, 'dancedWithRiftHerald': 0, 'deathsByEnemyChamps': 6, 'dodgeSkillShotsSmallWindow': 2, 'doubleAces': 0, 'dragonTakedowns': 0, 'earlyLaningPhaseGoldExpAdvantage': 0, 'effectiveHealAndShielding': 0, 'elderDragonKillsWithOpposingSoul': 0, 'elderDragonMultikills': 0, 'enemyChampionImmobilizations': 16, 'enemyJungleMonsterKills': 0, 'epicMonsterKillsNearEnemyJungler': 0, 'epicMonsterKillsWithin30SecondsOfSpawn': 0, 'epicMonsterSteals': 0, 'epicMonsterStolenWithoutSmite': 0, 'firstTurretKilled': 0, 'fistBumpParticipation': 0, 'flawlessAces': 0, 'fullTeamTakedown': 1, 'getTakedownsInAllLanesEarlyJungleAsLaner': 0, 'goldPerMinute': 286.44509240189035, 'hadOpenNexus': 0, 'immobilizeAndKillWithAlly': 1, 'initialBuffCount': 0, 'initialCrabCount': 0, 'jungleCsBefore10Minutes': 0, 'junglerTakedownsNearDamagedEpicMonster': 0, 'kTurretsDestroyedBeforePlatesFall': 0, 'kda': 1.1666666666666667, 'killAfterHiddenWithAlly': 0, 'killParticipation': 0.3684210526315789, 'killedChampTookFullTeamDamageSurvived': 0, 'killsNearEnemyTurret': 0, 'killsOnOtherLanesEarlyJungleAsLaner': 0, 'killsUnderOwnTurret': 0, 'killsWithHelpFromEpicMonster': 0, 'knockEnemyIntoTeamAndKill': 0, 'landSkillShotsEarlyGame': 0, 'laneMinionsFirst10Minutes': 42, 'laningPhaseGoldExpAdvantage': 0, 'legendaryCount': 0, 'lostAnInhibitor': 0, 'maxCsAdvantageOnLaneOpponent': 1, 'maxKillDeficit': 0, 'maxLevelLeadLaneOpponent': 1, 'moreEnemyJungleThanOpponent': 0, 'multiKillOneSpell': 0, 'multiTurretRiftHeraldCount': 0, 'multikills': 0, 'multikillsAfterAggressiveFlash': 0, 'outerTurretExecutesBefore10Minutes': 0, 'outnumberedKills': 0, 'outnumberedNexusKill': 0, 'perfectDragonSoulsTaken': 0, 'perfectGame': 0, 'pickKillWithAlly': 6, 'playedChampSelectPosition': 1, 'quickCleanse': 0, 'quickFirstTurret': 0, 'quickSoloKills': 0, 'riftHeraldTakedowns': 0, 'saveAllyFromDeath': 0, 'scuttleCrabKills': 0, 'skillshotsDodged': 38, 'skillshotsHit': 0, 'soloBaronKills': 0, 'soloKills': 0, 'stealthWardsPlaced': 7, 'takedownOnFirstTurret': 0, 'takedowns': 7, 'takedownsAfterGainingLevelAdvantage': 0, 'takedownsBeforeJungleMinionSpawn': 0, 'takedownsFirstXMinutes': 2, 'takedownsInAlcove': 0, 'takedownsInEnemyFountain': 0, 'teamBaronKills': 0, 'teamDamagePercentage': 0.13353853188344786, 'teamElderDragonKills': 0, 'teamRiftHeraldKills': 0, 'turretPlatesTaken': 0, 'turretsTakenWithRiftHerald': 0, 'twoWardsOneSweeperCount': 0, 'visionScoreAdvantageLaneOpponent': -0.37796372175216675, 'visionScorePerMinute': 0.4534942769625906, 'voidMonsterKill': 0, 'wardTakedowns': 0, 'wardTakedownsBefore20M': 0, 'wardsGuarded': 0, 'game_id': 7799959352, 'player_id': 'uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ'}
{'id_tree_primary': 8200, 'id_primary_1': 8229, 'id_primary_2': 8226, 'id_primary_3': 8210, 'id_primary_4': 8236, 'id_tree_sub': 8300, 'id_sub_1': 8347, 'id_sub_2': 8304, 'game_id': 7799959352, 'player_id': 'uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8sQ-TcgUDYLLjTLoZ94Lk6o-pu0ZtNRiUQ'}



In [10]:
display("Table cc_capacites", table_cc_capacites.shape, table_cc_capacites)
display("Table communication", table_communication.shape, table_communication)
display("Table damage", table_damage.shape, table_damage)
display("Table economie items", table_economie_items.shape, table_economie_items)
display("Table farming", table_farming.shape, table_farming)
display("Table figth", table_figth.shape, table_figth)
display("Table id joueur", table_identite_joueur.shape, table_identite_joueur)
display("Table objective structure", table_objective_structures.shape, table_objective_structures)
display("Table perf globale", table_perf_globale.shape, table_perf_globale)
# display("Table phase de lane", table_phase_de_lane.shape, table_phase_de_lane)
# display("Table soins soutien", table_soins_soutien.shape, table_soins_soutien)

'Table cc_capacites'

(10, 18)

,player_id,game_id,timeCCingOthers,totalTimeCCDealt,spell1Casts,spell2Casts,spell3Casts,spell4Casts,summoner1Casts,summoner1Id,summoner2Casts,summoner2Id,enemyChampionImmobilizations,abilityUses,skillshotsHit,skillshotsDodged,dodgeSkillShotsSmallWindow,landSkillShotsEarlyGame
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,10,46,234,15,47,8,3,4,6,14,12,304,18,23,1,3
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,26,185,63,0,78,8,15,11,4,4,57,149,0,22,1,0
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,8,66,101,24,49,6,2,4,2,12,16,180,0,38,2,0
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,0,0,177,39,27,12,6,21,5,4,0,255,64,18,1,15
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,35,211,122,70,37,9,5,7,4,4,22,238,102,17,0,22
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,40,124,64,23,92,9,5,4,7,14,0,188,0,64,1,0
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,10,489,308,94,98,5,3,4,20,11,6,505,14,21,2,1
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,23,340,104,13,63,5,4,12,4,4,13,185,175,22,0,50
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,10,238,144,61,45,9,4,4,6,21,0,259,46,44,2,7
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,74,300,51,54,38,8,5,4,7,14,132,151,28,58,1,5

'Table communication'

(10, 30)

,player_id,game_id,visionScore,wardsPlaced,wardsKilled,sightWardsBoughtInGame,visionWardsBoughtInGame,detectorWardsPlaced,allInPings,assistMePings,...,retreatPings,visionClearedPings,stealthWardsPlaced,controlWardsPlaced,visionScorePerMinute,wardTakedowns,wardTakedownsBefore20M,wardsGuarded,twoWardsOneSweeperCount,visionScoreAdvantageLaneOpponent
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,16,7,0,0,0,0,0,0,...,0,0,7,0,0.605231,0,0,0,0,-0.008785
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,19,9,0,0,0,0,0,0,...,0,0,9,0,0.735662,0,0,0,0,0.071445
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,12,7,0,0,0,0,0,0,...,0,0,7,0,0.453494,0,0,0,0,-0.377964
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,21,8,2,0,0,0,0,0,...,3,0,8,0,0.790268,2,2,0,0,0.760568
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,43,19,2,0,1,1,1,2,...,1,0,18,1,1.642165,2,2,1,0,-0.376080
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,16,7,0,0,0,0,0,6,...,1,0,7,0,0.610595,0,0,0,0,0.008862
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,18,1,2,0,1,1,0,0,...,2,0,0,1,0.686608,2,2,2,0,-0.066681
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,19,10,1,0,0,0,0,0,...,0,0,10,0,0.729048,1,0,0,0,0.607623
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,12,6,1,0,0,0,0,2,...,3,0,4,0,0.448871,1,1,0,0,-0.432001
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,70,27,6,0,2,2,1,0,...,1,0,25,2,2.632012,6,3,0,0,0.602769

'Table damage'

(10, 26)

,player_id,game_id,totalDamageDealt,totalDamageDealtToChampions,physicalDamageDealt,magicDamageDealt,trueDamageDealt,physicalDamageDealtToChampions,magicDamageDealtToChampions,trueDamageDealtToChampions,...,damagePerMinute,teamDamagePercentage,damageTakenOnTeamPercentage,totalHeal,totalHealsOnTeammates,totalDamageShieldedOnTeammates,totalUnitsHealed,effectiveHealAndShielding,saveAllyFromDeath,quickCleanse
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,161312,16623,138082,16050,7179,11795,3320,1508,...,621.731924,0.218514,0.240489,8456,0,0,1,0.000000,0,0
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,128380,13167,88142,0,40237,12112,0,1054,...,492.465904,0.173083,0.223096,4968,0,0,1,0.000000,0,0
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,120262,10159,2768,114273,3220,0,10100,58,...,379.952753,0.133539,0.155900,3248,0,0,1,0.000000,0,0
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,103799,9967,82901,9409,11489,7384,2582,0,...,372.780033,0.131018,0.217736,3776,0,0,1,0.000000,0,0
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,74056,26158,4303,57068,12684,1097,15486,9574,...,978.336200,0.343847,0.162779,2754,184,0,2,184.000000,0,0
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,176299,25660,165913,0,10385,20465,0,5195,...,959.701919,0.229129,0.271191,3500,0,0,1,0.000000,0,0
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,381451,15561,143600,77744,160105,6824,5806,2930,...,581.999505,0.138952,0.174098,12760,0,0,1,0.000000,0,0
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,163269,23296,14217,144488,4562,846,22449,0,...,871.306728,0.208024,0.103940,3181,0,0,1,0.000000,0,0
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,158547,32326,140847,12630,5070,26149,4408,1768,...,1209.006374,0.288650,0.230448,7384,0,0,1,0.000000,0,0
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,31338,15146,9040,16897,5399,4667,9245,1233,...,566.469708,0.135245,0.220323,6079,0,664,1,664.104797,0,0

'Table economie items'

(10, 14)

,player_id,game_id,goldEarned,goldSpent,itemsPurchased,consumablesPurchased,item0,item1,item2,item3,item4,item5,item6,goldPerMinute
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,10350,9300,24,2,3181,3153,2019,0,3047,2022,3340,387.095561
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,9506,8900,13,0,6676,3158,6692,6670,1036,0,3340,355.535079
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,7658,7550,18,2,1056,2503,1027,3173,6653,0,3340,286.445092
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,9127,8833,18,1,1055,3042,3078,3133,0,0,3340,341.380695
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,9971,8775,22,3,3871,6655,3020,4645,2508,2022,3364,372.943696
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,13156,12650,20,1,6631,2031,3006,3046,3031,3035,3340,492.041863
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,13650,12575,16,2,6333,4633,3073,3111,1057,1031,3364,510.533044
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,13869,13850,15,2,3171,0,6653,3089,4645,6655,3340,518.731388
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,15179,14000,21,1,1055,3508,3161,3094,3031,1018,3363,567.730399
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,11758,9815,23,4,3109,3190,1057,3869,3111,3075,3364,439.757722

'Table farming'

(10, 26)

,player_id,game_id,neutralMinionsKilled,totalMinionsKilled,totalAllyJungleMinionsKilled,totalEnemyJungleMinionsKilled,alliedJungleMonsterKills,enemyJungleMonsterKills,jungleCsBefore10Minutes,scuttleCrabKills,...,epicMonsterKillsNearEnemyJungler,epicMonsterKillsWithin30SecondsOfSpawn,junglerTakedownsNearDamagedEpicMonster,buffsStolen,maxCsAdvantageOnLaneOpponent,maxLevelLeadLaneOpponent,laningPhaseGoldExpAdvantage,earlyLaningPhaseGoldExpAdvantage,blastConeOppositeOpponentCount,fistBumpParticipation
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,0,233,0,0,0,0,0.0,0,...,0,0,0,0,27.00,1,0,0,0,0
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,107,6,91,2,55,2,60.0,1,...,1,0,0,0,4.00,0,0,0,0,0
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,0,176,0,0,0,0,0.0,0,...,0,0,0,0,1.00,1,0,0,0,0
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,0,141,0,0,0,0,0.0,0,...,0,0,0,0,0.00,1,0,0,0,0
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,4,49,4,0,1,0,0.0,0,...,0,0,0,0,21.75,1,0,0,0,0
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,0,220,0,0,0,0,0.0,0,...,0,0,1,0,5.00,2,0,0,0,1
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,257,9,165,35,109,32,84.0,7,...,0,1,0,0,153.00,5,0,0,0,4
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,4,269,0,0,0,0,0.0,0,...,0,0,0,0,105.00,3,1,0,0,0
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,4,198,0,4,0,6,0.0,0,...,0,0,0,0,68.00,2,1,0,0,3
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,2,29,0,0,0,0,2.0,0,...,0,0,1,0,10.00,2,0,0,0,2

'Table figth'

(10, 39)

,player_id,game_id,kills,deaths,assists,kda,doubleKills,tripleKills,quadraKills,pentaKills,...,bountyGold,maxKillDeficit,takedowns,takedownsFirstXMinutes,takedownsAfterGainingLevelAdvantage,takedownsBeforeJungleMinionSpawn,takedownOnFirstTurret,pickKillWithAlly,immobilizeAndKillWithAlly,knockEnemyIntoTeamAndKill
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,3,8,2,0.625000,0,0,0,0,...,437.717407,0,5,2,0,0,0,4,2,0
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,6,11,5,1.000000,0,0,0,0,...,169.444244,0,11,6,0,0,0,9,9,6
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,0,6,7,1.166667,0,0,0,0,...,0.000000,0,7,2,0,0,0,6,1,0
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,3,12,3,0.500000,0,0,0,0,...,0.000000,0,6,3,0,0,0,5,0,0
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,7,9,6,1.444444,1,0,0,0,...,753.084778,0,13,7,0,0,0,10,2,4
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,9,5,2,2.200000,0,0,0,0,...,0.000000,1,11,3,0,0,1,6,0,0
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,8,0,3,11.000000,1,0,0,0,...,0.000000,1,11,5,0,0,0,8,5,0
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,10,1,2,12.000000,1,0,0,0,...,0.000000,1,12,4,0,0,0,6,2,0
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,13,7,9,3.142857,3,0,0,0,...,0.000000,1,22,8,0,0,0,22,0,0
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,5,6,21,4.333333,0,0,0,0,...,0.000000,1,26,10,0,0,0,24,23,20

'Table id joueur'

(10, 18)

,player_id,game_id,riotIdGameName,riotIdTagline,summonerId,summonerLevel,championId,championName,champLevel,champExperience,participantId,teamId,lane,individualPosition,teamPosition,role,playedChampSelectPosition,championBan
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,Low Low Coast,TRUMP,xUEg1hcTKiJN8yXLSBfFcs-u0aRLl61aPjTlac8ACW4PmY...,176,39,Irelia,16,15255,1,100,JUNGLE,TOP,TOP,NONE,1,121
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,jujulepersqpuc,EUW,E_5sysaB33pHCmvzMAwex0blEshW2h8aLQ-w8Om2dNHp5o...,94,254,Vi,13,10022,2,100,JUNGLE,JUNGLE,JUNGLE,NONE,1,28
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,SaduSuricate5900,47895,iX6zvmMvEbWgmbdBk4zDAiTmvBYkuAO-rJtFFWVwE0FDym...,88,136,AurelionSol,15,13954,3,100,MIDDLE,MIDDLE,MIDDLE,SOLO,1,99
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,HakariKinji,SETT,EuMd0brNjSOwYIiMQE-2k10u0wTsIpPWW8tfYnBcwOlow30,443,81,Ezreal,14,12010,4,100,BOTTOM,BOTTOM,BOTTOM,CARRY,1,51
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,ThéEtMiel,EUW,YeheHOa0eS9gTe2aO32p1FogYDi2txBunQDlX9wHmPslOxk,522,161,Velkoz,13,10944,5,100,BOTTOM,UTILITY,UTILITY,SUPPORT,1,10
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,PhallusAttentif,EUW,m4HSA1KDrKsPAwi3cQX4mGtgOhwXqBSFH3lUVT2jfN78Kz...,54,86,Garen,17,17485,6,200,JUNGLE,TOP,TOP,NONE,1,268
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,Nevi,Pyke,MMpeywR0I489HJBRUAUEw1elIVM5iWKJdQ6xxWnLF5Rq9h...,494,102,Shyvana,17,17974,7,200,JUNGLE,JUNGLE,JUNGLE,NONE,1,35
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,Bimsness,EUW,jRCc5GW0LsjcTc7FomP-BFxs6jE95pTlcLhHRjEaISVL4QE,1005,800,Mel,17,17701,8,200,TOP,MIDDLE,MIDDLE,SOLO,1,119
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,LaraCroûteChaude,Lara,ZjNzLu71id3U0wz8Y80VPOJRc_IWC5cAvL8EBH_NgLuqFYI,54,901,Smolder,16,14953,9,200,BOTTOM,BOTTOM,BOTTOM,CARRY,1,902
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,DeltaAvenger,Delta,SgZUFI3ekibxTx3ttEQ7HPlNnwwNrikjKJkrmuQQknZM2t0,552,111,Nautilus,15,13734,10,200,BOTTOM,UTILITY,UTILITY,SUPPORT,1,17

'Table objective structure'

(10, 43)

,player_id,game_id,baronKills,dragonKills,inhibitorKills,turretKills,nexusKills,objectivesStolen,objectivesStolenAssists,damageDealtToObjectives,...,quickFirstTurret,multiTurretRiftHeraldCount,turretsTakenWithRiftHerald,takedownsInAlcove,takedownsInEnemyFountain,outnumberedNexusKill,hadOpenNexus,dancedWithRiftHerald,killsWithHelpFromEpicMonster,earliestBaron
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,0,0,0,0,0,0,0,3750,...,0,0,0,0,0,0,0,0,0,<NA>
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,0,1,0,0,0,0,0,5819,...,0,0,0,0,0,0,0,0,0,<NA>
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,0,0,0,0,0,0,0,486,...,0,0,0,0,0,0,0,0,0,<NA>
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,0,0,0,0,0,0,0,4017,...,0,0,0,0,0,0,0,0,0,<NA>
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,0,0,0,0,0,0,0,961,...,0,0,0,0,0,0,0,0,0,<NA>
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,0,0,2,5,0,0,0,20278,...,0,0,0,0,0,0,0,0,0,<NA>
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,0,2,0,1,0,0,0,46695,...,0,0,0,0,0,0,0,0,0,<NA>
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,0,1,1,4,0,0,0,15875,...,0,0,0,0,0,0,0,0,0,<NA>
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,0,0,0,1,1,0,0,6407,...,0,0,0,1,1,0,0,0,0,<NA>
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,0,0,1,0,0,0,0,3173,...,0,0,0,0,0,0,0,0,0,<NA>

'Table perf globale'

(10, 19)

,player_id,game_id,win,timePlayed,longestTimeSpentLiving,totalTimeSpentDead,gameEndedInSurrender,gameEndedInEarlySurrender,teamEarlySurrendered,inhibitorsLost,nexusLost,turretsLost,eligibleForProgression,lostAnInhibitor,flawlessAces,doubleAces,acesBefore15Minutes,fullTeamTakedown,perfectGame
0,qcCr6_8km5jGV3sJg05qVLecLwTol-k3dDDzhugM8ROrF5...,7799959352,False,1604,379,296,False,False,False,4,1,11,True,0,0,0,0,1,0
1,3HTvKgEQ2zsX23fvz_dVodB4iJGa7jFbD-bwCZfC1F1qY9...,7799959352,False,1604,646,389,False,False,False,4,1,11,True,0,0,0,0,1,0
2,uuhMlNBPDT3pLnQaGe2bXJ1CrxIuDxFD7dgcYKmdSnPL8s...,7799959352,False,1604,499,172,False,False,False,4,1,11,True,0,0,0,0,1,0
3,dwklZfe65dWfk2ahpkvyLDdU4VmpmiKFbP9W4Iv1lhpi5j...,7799959352,False,1604,361,299,False,False,False,4,1,11,True,0,0,0,0,1,0
4,b3jKwtQEvWhrHOKgQ7EdJCvrserlWbZ4UnRC_sXTThFsvt...,7799959352,False,1604,519,197,False,False,False,4,1,11,True,0,0,0,0,1,0
5,ClItTtga7tOfRWWw-Np7dIKexzBEN7xRwWRC-7LAXgj_nK...,7799959352,True,1604,461,164,False,False,False,0,0,0,True,0,0,0,0,0,0
6,l0rn2L3D6qnVcgkEm7gQQNUabxf8zW1CnOYJ5BI1Q5LbP0...,7799959352,True,1604,0,0,False,False,False,0,0,0,True,0,0,0,0,0,0
7,xL7PH4W4vy4Oz0w16ZgXU41ilyIFkMPIRpgNyKXUE7X7BT...,7799959352,True,1604,547,28,False,False,False,0,0,0,True,0,0,0,0,0,0
8,DkcZQVZ8faLzGb__fwTeuefkHXUidshGIUkBiv36_8vig-...,7799959352,True,1604,470,220,False,False,False,0,0,0,True,0,0,0,0,0,0
9,IMjlDrchPi-fdzmQWEhRUcOVV4BWqJHd6t5LSZdREK40ti...,7799959352,True,1604,524,94,False,False,False,0,0,0,True,0,0,0,0,0,0

In [ ]:
def get_max_length(col : pd.Series):
    x = 0
    for i in col.astype(str):
        if len(i) > x:
            x = len(i)
    return x

def create_schema(table : pd.DataFrame, table_name : str):
    type_map = {
        "int64": "INTEGER",
        "float64": "REAL",
        "object": "VARCHAR",
        "bool": "BOOLEAN",
        "datetime64[ns]": "TIMESTAMP",
        "str": "VARCHAR"
    }

    columns = []
    for col in table.columns:
        col_type = type_map.get(table[col].dtype.name, "TEXT")
        columns.append(f"{col} {col_type}")

    txt = f"CREATE TABLE {table_name} (\n    " + ",\n    ".join(columns) + ","+ f"\n\tCONSTRAINT pk_{table_name}\n\t\tPRIMARY KEY (puuid, game_id)\n);"
    return txt

tables = {
    "communication":        table_communication,
    "cc_capacites":         table_cc_capacites,
    "damage":               table_damage,
    "economie_items":       table_economie_items,
    "farming":              table_farming,
    "fight":                table_figth,
    "identite_joueur":      table_identite_joueur,
    "objective_structures": table_objective_structures,
    "perf_globale":         table_perf_globale,
}

schemas = [create_schema(df, name) for name, df in tables.items()]

with open(r"src_sql\schemas.txt", "w", encoding="utf-8") as f:
    f.write("\n\n".join(schemas))

In [11]:
table_objective_structures.dtypes

player_id                               str
game_id                               int64
baronKills                            int64
dragonKills                           int64
inhibitorKills                        int64
turretKills                           int64
nexusKills                            int64
objectivesStolen                      int64
objectivesStolenAssists               int64
damageDealtToObjectives               int64
damageDealtToBuildings                int64
damageDealtToEpicMonsters             int64
damageDealtToTurrets                  int64
firstTowerKill                         bool
firstTowerAssist                       bool
turretTakedowns                       int64
nexusTakedowns                        int64
inhibitorTakedowns                    int64
turretPlatesTaken                     int64
baronTakedowns                        int64
riftHeraldTakedowns                   int64
dragonTakedowns                       int64
epicMonsterSteals                     int64
epicMonsterStolenWithoutSmite         int64
teamBaronKills                        int64
teamElderDragonKills                  int64
teamRiftHeraldKills                   int64
soloBaronKills                        int64
elderDragonKillsWithOpposingSoul      int64
elderDragonMultikills                 int64
perfectDragonSoulsTaken               int64
kTurretsDestroyedBeforePlatesFall     int64
outerTurretExecutesBefore10Minutes    int64
quickFirstTurret                      int64
multiTurretRiftHeraldCount            int64
turretsTakenWithRiftHerald            int64
takedownsInAlcove                     int64
takedownsInEnemyFountain              int64
outnumberedNexusKill                  int64
hadOpenNexus                          int64
dancedWithRiftHerald                  int64
killsWithHelpFromEpicMonster          int64
earliestBaron                         Int64
dtype: object

In [5]:
cnt = 0
total = 467
import time

for i in range(total):
    cnt += 1
    prct = round((cnt/total)*100, 2)
    print(f"\tNombre de game récupérées et traitées {cnt}/{total} ({prct}%)", end = '\r')
    time.sleep(0.1)